### PR TITLE
[TwigComponent] Fix LiveComponent namespace mapping

### LINKED ISSUE #1754: [LiveComponent] Live component will not render depending on Twig invocation syntax
# Environment

* Ubuntu/Pop!_OS
* PHP 8.3 inside Docker
* Symfony 6.4
* `symfony/ux-twig-component` v2.16.0
* `symfony/ux-live-component` v2.16.0

# Situation

My problem appears to be related to earlier (closed) tickets:

* April 2023: [[TwigComponent] New HTML syntax marked as embedded in all cases - fails for live components #810](https://github.com/symfony/ux/issues/810)
* October 2023: [Unable to find custom template for UX components with twig:component syntax #1205](https://github.com/symfony/ux/issues/1205)
* February 2024: [[LiveComponent] Getting "Cannot find a template matching "a67ec1ad40dd8f6b6934cb852ed6d2f9". Cache may be corrupt."... all the time #1493](https://github.com/symfony/ux/issues/1493)

It may well, however, be related to my particular configuration and I'm very happy for any feedback and ideas on this. I can also try to further reduce the problem if you like.

**Twig configuration** (`config/packages/twig.yaml`)
```yaml
twig:
    debug: false
    auto_reload: false
    form_themes:
        - 'Cockpit/FormLayout.html.twig'
    strict_variables: false
    exception_controller: null
    paths:
        '%kernel.project_dir%/templates/Cockpit': Cockpit
        '%kernel.project_dir%/templates/Frontend': Frontend
        '%kernel.project_dir%/templates/Phoenix': Phoenix
        '%kernel.project_dir%/templates/SSO': SSO
    default_path: '%kernel.project_dir%/templates'
    file_name_pattern: '*.twig'

when@dev:
    twig:
        auto_reload: true
        debug: true
        strict_variables: true

when@test:
    twig:
        strict_variables: true
```

**Twig component configurations** (`config/packages/twig_component.yaml`)
```yaml
twig_component:
    anonymous_template_directory: 'Components/'
    defaults:
        # Namespace & directory for components
        App\Twig\Components\: 'Components/'
```

**Live components routing** (`config/routes/ux_live_component.yaml`)
```yaml
live_component:
    resource: '@LiveComponentBundle/config/routes.php'
    prefix: '/_components'
```

**Services configuration** (`config/services.yaml`)
```yaml
(...)
services:
    App\Twig\Components\:
      resource: '../src/Twig/Components/*'
(...)
```

**Live component PHP class** (`src/Twig/Components/Cockpit/MatchingScheduleForm.php`)
```php
<?php

declare(strict_types=1);

namespace App\Twig\Components\Cockpit;

use Symfony\UX\LiveComponent\Attribute\AsLiveComponent;
use Symfony\UX\LiveComponent\DefaultActionTrait;

#[AsLiveComponent]
class MatchingScheduleForm
{
    use DefaultActionTrait;
}
```

**Live component Twig template** (`templates/Components/Cockpit/MatchingScheduleForm.html.twig`)
```twig
<div {{ attributes }}>
    Hello
</div>
```

**Twig template that tries to render the component** (`templates/Cockpit/Admin/Configuration/Configuration.html.twig`)
```twig
<html>
<body>
    {# Option 1: Self-closing style #}
    <twig:Cockpit:MatchingScheduleForm/> {# Works! #}

    {# Option 2: Twig expression style #}
    {{ component('Cockpit:MatchingScheduleForm') }} {# Works! #}
</body>
</html>
```

# Problem

The above setup works. I do get errors when I use different component embed syntaxes, though:

```twig
<html>
<body>
    {# Option 3: Opening and closing tag #}
    <twig:Cockpit:MatchingScheduleForm></twig:Cockpit:MatchingScheduleForm>
    {# Error: Error rendering "Cockpit:MatchingScheduleForm" component: Cannot find a match for template "Admin/Configuration/Configuration.html.twig". Cache may be corrupt. #}

    {# Option 4: Component tag syntax #}
    {% component 'Cockpit:MatchingScheduleForm' %}{% endcomponent %}
    {# Error: Error rendering "Cockpit:MatchingScheduleForm" component: Cannot find a match for template "Admin/Configuration/Configuration.html.twig". Cache may be corrupt. #}
</body>
</html>
```

Using these syntaxes results in the following Twig `RuntimeError`...
```
Twig\Error\RuntimeError (/srv/ml/vendor/twig/twig/src/Error/RuntimeError.php:20) {
  -lineno: 3
  -name: "@Cockpit/Admin/Configuration/Configuration.html.twig"
  -rawMessage: "Error rendering "Cockpit:MatchingScheduleForm" component: Cannot find a match for template "Admin/Configuration/Configuration.html.twig". Cache may be corrupt."
  -sourcePath: "/srv/ml/templates/Cockpit/Admin/Configuration/Configuration.html.twig"
  -sourceCode: """
    <html>
    <body>
    {% component 'Cockpit:MatchingScheduleForm' %}{% endcomponent %} {# error #}
    </body>
    </html>
    """
}
```
... and the following `RuntimeException`:

```
RuntimeException
Cannot find a match for template "Admin/Configuration/Configuration.html.twig". Cache may be corrupt.
```

# Trying to fix it

`rm -rf var/cache/` does not get rid of the error.

# Details

<details><summary>Twig RuntimeError stacktrace</summary>
<pre>
Twig\Error\RuntimeError:
Error rendering "Cockpit:MatchingScheduleForm" component: Cannot find a match for template "Admin/Configuration/Configuration.html.twig". Cache may be corrupt.

  at templates/Cockpit/Admin/Configuration/Configuration.html.twig:3
  at Symfony\UX\TwigComponent\Twig\ComponentExtension->throwRuntimeError('Cockpit:MatchingScheduleForm', object(RuntimeException))
     (vendor/symfony/ux-twig-component/src/Twig/ComponentExtension.php:80)
  at Symfony\UX\TwigComponent\Twig\ComponentExtension->startEmbeddedComponentRender('Cockpit:MatchingScheduleForm', array(), array('client' => object(Client), 'configurationForm' => object(FormView), 'placeholders' => array(object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder)), 'program' => object(Program), 'showConfigurations' => false, 'app' => object(AppVariable), 'global' => array('accessibleClients' => array(array('code' => object(ClientCode), 'name' => 'xyz', 'officialDomain' => 'http://xyz.localhost'), array('code' => object(ClientCode), 'name' => 'xyz', 'officialDomain' => 'http://xyz.localhost'), array('code' => object(ClientCode), 'name' => 'xyz', 'officialDomain' => 'http://xyz.localhost')), 'currentCalendarWeek' => object(CalendarWeek), 'release' => 'local', 'settings' => object(CockpitSettings))), 'Admin/Configuration/Configuration.html.twig', 944708181)
     (var/cache/dev/twig/b0/b07221026fe44f7acedce0b9da94300b.php:51)
  at __TwigTemplate_e7a7b0325ec24a14e1887aca70b34379->doDisplay(array('client' => object(Client), 'configurationForm' => object(FormView), 'placeholders' => array(object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder)), 'program' => object(Program), 'showConfigurations' => false, 'app' => object(AppVariable), 'global' => array('accessibleClients' => array(array('code' => object(ClientCode), 'name' => 'xyz', 'officialDomain' => 'http://xyz.localhost'), array('code' => object(ClientCode), 'name' => 'xyz', 'officialDomain' => 'http://xyz.localhost'), array('code' => object(ClientCode), 'name' => 'xyz', 'officialDomain' => 'http://xyz.localhost')), 'currentCalendarWeek' => object(CalendarWeek), 'release' => 'local', 'settings' => object(CockpitSettings))), array())
     (vendor/twig/twig/src/Template.php:394)
  at Twig\Template->displayWithErrorHandling(array('client' => object(Client), 'configurationForm' => object(FormView), 'placeholders' => array(object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder)), 'program' => object(Program), 'showConfigurations' => false, 'app' => object(AppVariable), 'global' => array('accessibleClients' => array(array('code' => object(ClientCode), 'name' => 'xyz', 'officialDomain' => 'http://xyz.localhost'), array('code' => object(ClientCode), 'name' => 'xyz', 'officialDomain' => 'http://xyz.localhost'), array('code' => object(ClientCode), 'name' => 'xyz', 'officialDomain' => 'http://xyz.localhost')), 'currentCalendarWeek' => object(CalendarWeek), 'release' => 'local', 'settings' => object(CockpitSettings))), array())
     (vendor/twig/twig/src/Template.php:367)
  at Twig\Template->display(array('client' => object(Client), 'configurationForm' => object(FormView), 'placeholders' => array(object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder)), 'program' => object(Program), 'showConfigurations' => false))
     (vendor/twig/twig/src/Template.php:379)
  at Twig\Template->render(array('client' => object(Client), 'configurationForm' => object(FormView), 'placeholders' => array(object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder)), 'program' => object(Program), 'showConfigurations' => false))
     (vendor/twig/twig/src/TemplateWrapper.php:38)
  at Twig\TemplateWrapper->render(array('client' => object(Client), 'configurationForm' => object(FormView), 'placeholders' => array(object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder)), 'program' => object(Program), 'showConfigurations' => false))
     (vendor/twig/twig/src/Environment.php:280)
  at Twig\Environment->render('@Cockpit/Admin/Configuration/Configuration.html.twig', array('client' => object(Client), 'configurationForm' => object(FormView), 'placeholders' => array(object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder)), 'program' => object(Program), 'showConfigurations' => false))
     (vendor/symfony/framework-bundle/Controller/AbstractController.php:448)
  at Symfony\Bundle\FrameworkBundle\Controller\AbstractController->doRenderView('@Cockpit/Admin/Configuration/Configuration.html.twig', null, array('client' => object(Client), 'configurationForm' => object(FormView), 'placeholders' => array(object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder)), 'program' => object(Program), 'showConfigurations' => false), 'render')
     (vendor/symfony/framework-bundle/Controller/AbstractController.php:453)
  at Symfony\Bundle\FrameworkBundle\Controller\AbstractController->doRender('@Cockpit/Admin/Configuration/Configuration.html.twig', null, array('client' => object(Client), 'configurationForm' => object(Form), 'placeholders' => array(object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder)), 'program' => object(Program), 'showConfigurations' => false), null, 'render')
     (vendor/symfony/framework-bundle/Controller/AbstractController.php:253)
  at Symfony\Bundle\FrameworkBundle\Controller\AbstractController->render('@Cockpit/Admin/Configuration/Configuration.html.twig', array('client' => object(Client), 'configurationForm' => object(Form), 'placeholders' => array(object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder)), 'program' => object(Program), 'showConfigurations' => false), null)
     (src/Controller/Traits/CspAllowedHostTrait.php:31)
  at App\Cockpit\Controller\Admin\Configuration\ConfigurationController->renderWithCspAllowedHost('@Cockpit/Admin/Configuration/Configuration.html.twig', array('client' => object(Client), 'configurationForm' => object(Form), 'placeholders' => array(object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder)), 'program' => object(Program), 'showConfigurations' => false), null, '\'unsafe-eval\'')
     (src/Cockpit/Controller/Admin/Configuration/ConfigurationController.php:131)
  at App\Cockpit\Controller\Admin\Configuration\ConfigurationController->newConfiguration(object(Program), object(Request))
     (vendor/symfony/http-kernel/HttpKernel.php:181)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:76)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:197)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php:35)
  at Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
     (vendor/autoload_runtime.php:29)
  at require_once('/srv/ml/vendor/autoload_runtime.php')
     (public/index.php:7)
</pre>
</details>

<details><summary>RuntimeException stacktrace</summary>
<pre>
RuntimeException:
Cannot find a match for template "Admin/Configuration/Configuration.html.twig". Cache may be corrupt.

  at vendor/symfony/ux-live-component/src/Twig/TemplateMap.php:42
  at Symfony\UX\LiveComponent\Twig\TemplateMap->obscuredName('Admin/Configuration/Configuration.html.twig')
     (vendor/symfony/ux-live-component/src/Util/LiveControllerAttributesCreator.php:85)
  at Symfony\UX\LiveComponent\Util\LiveControllerAttributesCreator->attributesForRendering(object(MountedComponent), object(ComponentMetadata), false)
     (vendor/symfony/ux-live-component/src/EventListener/AddLiveAttributesSubscriber.php:102)
  at Symfony\UX\LiveComponent\EventListener\AddLiveAttributesSubscriber->getLiveAttributes(object(MountedComponent), object(ComponentMetadata))
     (vendor/symfony/ux-live-component/src/EventListener/AddLiveAttributesSubscriber.php:51)
  at Symfony\UX\LiveComponent\EventListener\AddLiveAttributesSubscriber->onPreRender(object(PreRenderEvent), 'Symfony\\UX\\TwigComponent\\Event\\PreRenderEvent', object(TraceableEventDispatcher))
     (vendor/symfony/event-dispatcher/Debug/WrappedListener.php:116)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(object(PreRenderEvent), 'Symfony\\UX\\TwigComponent\\Event\\PreRenderEvent', object(TraceableEventDispatcher))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:220)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners(array(object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'Symfony\\UX\\TwigComponent\\Event\\PreRenderEvent', object(PreRenderEvent))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:56)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch(object(PreRenderEvent), 'Symfony\\UX\\TwigComponent\\Event\\PreRenderEvent')
     (vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:139)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(object(PreRenderEvent))
     (vendor/symfony/ux-twig-component/src/ComponentRenderer.php:141)
  at Symfony\UX\TwigComponent\ComponentRenderer->preRender(object(MountedComponent), array('client' => object(Client), 'configurationForm' => object(FormView), 'placeholders' => array(object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder)), 'program' => object(Program), 'showConfigurations' => false, 'app' => object(AppVariable), 'global' => array('accessibleClients' => array(array('code' => object(ClientCode), 'name' => 'xyz', 'officialDomain' => 'http://xyz.localhost'), array('code' => object(ClientCode), 'name' => 'xyz', 'officialDomain' => 'http://xyz.localhost'), array('code' => object(ClientCode), 'name' => 'xyz', 'officialDomain' => 'http://xyz.localhost')), 'currentCalendarWeek' => object(CalendarWeek), 'release' => 'local', 'settings' => object(CockpitSettings)), '__embedded' => true))
     (vendor/symfony/ux-twig-component/src/ComponentRenderer.php:98)
  at Symfony\UX\TwigComponent\ComponentRenderer->startEmbeddedComponentRender('Cockpit:MatchingScheduleForm', array(), array('client' => object(Client), 'configurationForm' => object(FormView), 'placeholders' => array(object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder)), 'program' => object(Program), 'showConfigurations' => false, 'app' => object(AppVariable), 'global' => array('accessibleClients' => array(array('code' => object(ClientCode), 'name' => 'xyz', 'officialDomain' => 'http://xyz.localhost'), array('code' => object(ClientCode), 'name' => 'xyz', 'officialDomain' => 'http://xyz.localhost'), array('code' => object(ClientCode), 'name' => 'xyz', 'officialDomain' => 'http://xyz.localhost')), 'currentCalendarWeek' => object(CalendarWeek), 'release' => 'local', 'settings' => object(CockpitSettings)), '__embedded' => true), 'Admin/Configuration/Configuration.html.twig', 944708181)
     (vendor/symfony/ux-twig-component/src/Twig/ComponentExtension.php:78)
  at Symfony\UX\TwigComponent\Twig\ComponentExtension->startEmbeddedComponentRender('Cockpit:MatchingScheduleForm', array(), array('client' => object(Client), 'configurationForm' => object(FormView), 'placeholders' => array(object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder)), 'program' => object(Program), 'showConfigurations' => false, 'app' => object(AppVariable), 'global' => array('accessibleClients' => array(array('code' => object(ClientCode), 'name' => 'xyz', 'officialDomain' => 'http://xyz.localhost'), array('code' => object(ClientCode), 'name' => 'xyz', 'officialDomain' => 'http://xyz.localhost'), array('code' => object(ClientCode), 'name' => 'xyz', 'officialDomain' => 'http://xyz.localhost')), 'currentCalendarWeek' => object(CalendarWeek), 'release' => 'local', 'settings' => object(CockpitSettings))), 'Admin/Configuration/Configuration.html.twig', 944708181)
     (var/cache/dev/twig/b0/b07221026fe44f7acedce0b9da94300b.php:51)
  at __TwigTemplate_e7a7b0325ec24a14e1887aca70b34379->doDisplay(array('client' => object(Client), 'configurationForm' => object(FormView), 'placeholders' => array(object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder)), 'program' => object(Program), 'showConfigurations' => false, 'app' => object(AppVariable), 'global' => array('accessibleClients' => array(array('code' => object(ClientCode), 'name' => 'xyz', 'officialDomain' => 'http://xyz.localhost'), array('code' => object(ClientCode), 'name' => 'xyz', 'officialDomain' => 'http://xyz.localhost'), array('code' => object(ClientCode), 'name' => 'xyz', 'officialDomain' => 'http://xyz.localhost')), 'currentCalendarWeek' => object(CalendarWeek), 'release' => 'local', 'settings' => object(CockpitSettings))), array())
     (vendor/twig/twig/src/Template.php:394)
  at Twig\Template->displayWithErrorHandling(array('client' => object(Client), 'configurationForm' => object(FormView), 'placeholders' => array(object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder)), 'program' => object(Program), 'showConfigurations' => false, 'app' => object(AppVariable), 'global' => array('accessibleClients' => array(array('code' => object(ClientCode), 'name' => 'xyz', 'officialDomain' => 'http://xyz.localhost'), array('code' => object(ClientCode), 'name' => 'xyz', 'officialDomain' => 'http://xyz.localhost'), array('code' => object(ClientCode), 'name' => 'xyz', 'officialDomain' => 'http://xyz.localhost')), 'currentCalendarWeek' => object(CalendarWeek), 'release' => 'local', 'settings' => object(CockpitSettings))), array())
     (vendor/twig/twig/src/Template.php:367)
  at Twig\Template->display(array('client' => object(Client), 'configurationForm' => object(FormView), 'placeholders' => array(object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder)), 'program' => object(Program), 'showConfigurations' => false))
     (vendor/twig/twig/src/Template.php:379)
  at Twig\Template->render(array('client' => object(Client), 'configurationForm' => object(FormView), 'placeholders' => array(object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder)), 'program' => object(Program), 'showConfigurations' => false))
     (vendor/twig/twig/src/TemplateWrapper.php:38)
  at Twig\TemplateWrapper->render(array('client' => object(Client), 'configurationForm' => object(FormView), 'placeholders' => array(object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder)), 'program' => object(Program), 'showConfigurations' => false))
     (vendor/twig/twig/src/Environment.php:280)
  at Twig\Environment->render('@Cockpit/Admin/Configuration/Configuration.html.twig', array('client' => object(Client), 'configurationForm' => object(FormView), 'placeholders' => array(object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder)), 'program' => object(Program), 'showConfigurations' => false))
     (vendor/symfony/framework-bundle/Controller/AbstractController.php:448)
  at Symfony\Bundle\FrameworkBundle\Controller\AbstractController->doRenderView('@Cockpit/Admin/Configuration/Configuration.html.twig', null, array('client' => object(Client), 'configurationForm' => object(FormView), 'placeholders' => array(object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder)), 'program' => object(Program), 'showConfigurations' => false), 'render')
     (vendor/symfony/framework-bundle/Controller/AbstractController.php:453)
  at Symfony\Bundle\FrameworkBundle\Controller\AbstractController->doRender('@Cockpit/Admin/Configuration/Configuration.html.twig', null, array('client' => object(Client), 'configurationForm' => object(Form), 'placeholders' => array(object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder)), 'program' => object(Program), 'showConfigurations' => false), null, 'render')
     (vendor/symfony/framework-bundle/Controller/AbstractController.php:253)
  at Symfony\Bundle\FrameworkBundle\Controller\AbstractController->render('@Cockpit/Admin/Configuration/Configuration.html.twig', array('client' => object(Client), 'configurationForm' => object(Form), 'placeholders' => array(object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder)), 'program' => object(Program), 'showConfigurations' => false), null)
     (src/Controller/Traits/CspAllowedHostTrait.php:31)
  at App\Cockpit\Controller\Admin\Configuration\ConfigurationController->renderWithCspAllowedHost('@Cockpit/Admin/Configuration/Configuration.html.twig', array('client' => object(Client), 'configurationForm' => object(Form), 'placeholders' => array(object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder), object(Placeholder)), 'program' => object(Program), 'showConfigurations' => false), null, '\'unsafe-eval\'')
     (src/Cockpit/Controller/Admin/Configuration/ConfigurationController.php:131)
  at App\Cockpit\Controller\Admin\Configuration\ConfigurationController->newConfiguration(object(Program), object(Request))
     (vendor/symfony/http-kernel/HttpKernel.php:181)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:76)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:197)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php:35)
  at Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
     (vendor/autoload_runtime.php:29)
  at require_once('/srv/ml/vendor/autoload_runtime.php')
     (public/index.php:7)
</pre>
</details>

### PR DESCRIPTION
**Pull request by smnandre**
I believe this modification fix #1754

**Original problem**

If you render a template @Acme/dashboard.html.twig, embedded Components (live or twig) referenced wrong template (dashboard.html.twig here), making LiveComponent impossible to rerender (this file beeing not referenced in the TemplateMap).

This behaviour was introduced in #1082 (and worked then). But i'm convinced all the work/changes made by Ryan to fix the embed bug (#1247 and related) made this obselete (and in this particular situation even originates a bug)

All tests are green, and i'd like to test it more heavily... but before that : do you think this is a bug fix or is there some kind of BC break here?

### CODE REVIEW

**Review by WebMamba — COMMENTED** [review]
No I don't think this is a BC break but a fix to a bug

**Review by kbond — COMMENTED** [review]
I think bug also.

File: src/TwigComponent/src/Twig/TemplateNameParser.php [hunk 1]
```diff
@@ -11,21 +11,24 @@
 
 namespace Symfony\UX\TwigComponent\Twig;
 
+/**
+ * @internal
+ */
 final class TemplateNameParser
```
Comment (pierredup) [inline src/TwigComponent/src/Twig/TemplateNameParser.php:17]: Is this class still necessary?

It's not parsing a template name anymore, but just validating the template name, which already happens in `Twig\Loader\FilesystemLoader::parseName` (in all scenarios in this class, it's just returning the name as-is, so it's just duplicating the validation logic from `FilesystemLoader`)

Comment (smnandre) [reply src/TwigComponent/src/Twig/TemplateNameParser.php:17]: But we cannot remove it because BC i guess.. @kbond ?

**Comment by smnandre** [comment]
Ready to merge (confirmed to fix the original issue https://github.com/symfony/ux/issues/1754#issuecomment-2076521487 ) when you want guys ☺️

File: src/TwigComponent/src/Twig/TemplateNameParser.php (hunk 1 above)
Comment (kbond) [reply src/TwigComponent/src/Twig/TemplateNameParser.php:17]: I consider this class internal so let's remove if not required anymore.

**Comment by kbond** [comment]
Thanks Simon.

**Comment by melbings** [comment]
Thank you, everyone!

**Comment by sneakyvv** [comment]
Hi Simon (@smnandre),

It seems it _does_ introduce a BC break, because my templates are no longer found now :\ 

I'll investigate why this is happening, but since the namespace is no longer stripped (https://github.com/symfony/ux/pull/1772/files#diff-13fd1de1f292494959041e77eee8b739859160fb2f7da4290d278c9bdcdcb907L28). It cannot be found with the template name including the namespace.

However... perhaps it should be in the template map _WITH_ a namespace....
which I also talked about in #1082 & #1070, but then assumed that the map was correct in stripping the namespace... I'm investigating whether this is correct or not now.

**Comment by sneakyvv** [comment]
I went down to the TemplateIterator code, and it seems that my "fix" in #1070 was not correct.

Shopware, in which I'm using Live components, is [stripping the namespace in its decorated version of the template iterator](https://github.com/shopware/shopware/commit/294d02f9dfdb0b62030fddd726e0ac68fcb0f456#diff-02e4d0a4eeabb8c58eb252756232ccc02694745068bdc2f674e1b63d3cf6d0ffR40). 
Don't know why, but it obviously goes against the normal usage of namespaces 😞 

So to conclude: the TemplateNameParser is indeed obsolete now. I'll create a new PR to remove it!
