### PR TITLE
[Map] Introduce `ux_map.google_maps.default_map_id` configuration

### LINKED ISSUE #2306: [Map] Google map ID config when using a marker
Hi there,

I'm playing around with UX map with my Google account, and while I'm following a simple example from doc, I get an unexpected behavior;

```php
#[Route('/event/{id}', name: 'app_test')]
public function test(EventETT $event): Response
{
        $point = new Point(48.858370, 2.294481);

        $map = (new Map('default'))
            ->zoom(10)
            ->addMarker(new Marker($point))
            ->center($point)
        ;

        return $this->render('skeletons/event/show.html.twig', [
            'event' => $event,
            'map' => $map
        ]);
}
```
I think this is a very simple example based on docs, if I didn't made any mistake, I get the following behavior:

image

`Google Maps can't load correctly on this page.` in the canvas, and `The map is being initialized without a valid map ID, which prevents the use of advanced markers.` Well, OK, let's do this; I created a map ID on my cloud console, and then... I don't really know how to load it in my app. Here's [the official doc about it](https://developers.google.com/maps/documentation/get-map-id#javascript).

So here I am: did I made a mistake if I get stuck like this? If so, can I improve the doc to help future devs to not get stuck as me? If I didn't made a mistake, is there an elegant, already provided way to add this map ID? I expect a en variable the same way than `GOOGLE_MAPS_API_KEY` but where to mix them up to create the final url with map ID? I suppose it's related to `UX_MAP_DSN` but before going deeper and maybe propose an update here, I prefer asking here, because it's a veeery basic step where I'm stuck, so I wonder if there is an already implemented way of dealing with this. And if so, I would add it to the doc!

### PR DESCRIPTION
**Pull request by Kocal**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes 
| Issues        | Fix #2306 
| License       | MIT

With this modification, I can configure a default Google Maps `mapId`:
```yaml
# config/packages/ux_map.yaml
ux_map:
    # https://symfony.com/bundles/ux-map/current/index.html#available-renderers
    renderer: '%env(resolve:default::UX_MAP_DSN)%'
    google_maps:
        default_map_id: abcdefgh123456789
```
without having to manually pass the `mapId` when creating a `Map`:
```php
// use default mapId
$map = (new Map());
    ->center(new Point(48.8566, 2.3522))
    ->zoom(6);

// use default mapId
$map2 = (clone $map)
    ->options(new GoogleOptions());

// use custom mapId
$map3 = (clone $map)
    ->options(new GoogleOptions(mapId: 'foobar));
```

### CODE REVIEW

File: src/Map/src/Bridge/Google/src/GoogleOptions.php [hunk 1]
```diff
@@ -46,6 +46,11 @@ public function mapId(?string $mapId): self
         return $this;
     }
 
+    public function hasMapId(): bool
+    {
+        return null !== $this->mapId;
+    }
```
Comment (Kocal) [inline src/Map/src/Bridge/Google/src/GoogleOptions.php:52]: Maybe we can make properties public..?

File: src/Map/CHANGELOG.md [hunk 2]
```diff
@@ -1,4 +1,10 @@
 # CHANGELOG
+ 
+## 2.22
+
+-   Add method `Symfony\UX\Map\Renderer\AbstractRenderer::tapOptions()`, to allow Renderer to modify options before rendering a Map.
```
Comment (smnandre) [inline src/Map/CHANGELOG.md:5]:
```suggestion
-   Add method `Symfony\UX\Map\Renderer\AbstractRenderer::tapOptions()`, to  modify options before rendering a Map
```

File: src/Map/CHANGELOG.md [hunk 3]
```diff
@@ -1,4 +1,10 @@
...
+-   Add configuration `ux_map.google_maps.default_map_id` to automatically set the map id for all maps
```
Comment (smnandre) [inline src/Map/CHANGELOG.md]:
```suggestion
-   Add `ux_map.google_maps.default_map_id` configuration to set the Google ``Map ID``
```

File: src/Map/src/Bridge/Google/CHANGELOG.md [hunk 4]
```diff
@@ -1,5 +1,10 @@
 # CHANGELOG
 
+## 2.22
+
+-   Add argument `$defaultMapId` to `Symfony\UX\Map\Bridge\Google\Renderer\GoogleRendererFactory` constructor
+-   Add argument `$defaultMapId` to `Symfony\UX\Map\Bridge\Google\Renderer\GoogleRenderer` constructor
```
Comment (smnandre) [inline src/Map/src/Bridge/Google/CHANGELOG.md:7]: - Add support for Google ``Map ID``

File: src/Map/src/Bridge/Google/src/GoogleOptions.php (hunk 1 above)
Comment (smnandre) [reply src/Map/src/Bridge/Google/src/GoogleOptions.php:52]: As @nicolas-grekas explained me (more than once.. i'm a slow learner), it's harder to maintain BC with property or named arguments than good old-fashioned methods :)

File: src/Map/src/Renderer/AbstractRenderer.php [hunk 5]
```diff
@@ -39,6 +51,8 @@ final public function renderMap(Map $map, array $attributes = []): string
             $map->options($defaultMapOptions);
         }
 
+        $map->options($this->tapOptions($map->getOptions()));
```
Comment (smnandre) [inline src/Map/src/Renderer/AbstractRenderer.php:54]: Not sure to get the name

File: src/Map/src/UXMapBundle.php [hunk 6]
```diff
@@ -44,6 +44,12 @@ public function configure(DefinitionConfigurator $definition): void
         $rootNode
             ->children()
                 ->scalarNode('renderer')->defaultNull()->end()
+                ->arrayNode('google_maps')
+                    ->addDefaultsIfNotSet()
+                    ->children()
+                        ->scalarNode('default_map_id')->defaultNull()->end()
+                    ->end()
+                ->end()
```
Comment (smnandre) [inline src/Map/src/UXMapBundle.php:52]: Genuine question here, could this be done in a more generic way with arraynodes with open prototypes? I fear having to type options in the MapBundle will quickly defeat the main abrstaction/contract purpose of this bundle

File: src/Map/src/UXMapBundle.php [hunk 7]
```diff
@@ -75,9 +81,17 @@ public function loadExtension(array $config, ContainerConfigurator $container, C
...
             if (ContainerBuilder::willBeAvailable('symfony/ux-'.$name.'-map', $bridge['renderer_factory'], ['symfony/ux-map'])) {
                 $container->services()
-                    ->set('ux_map.renderer_factory.'.$name, $bridge['renderer_factory'])
+                    ->set($rendererFactoryName = 'ux_map.renderer_factory.'.$name, $bridge['renderer_factory'])
                     ->parent('ux_map.renderer_factory.abstract')
                     ->tag('ux_map.renderer_factory');
+
+                if ('google' === $name) {
+                    $container->services()
+                        ->get($rendererFactoryName)
```
Comment (smnandre) [inline src/Map/src/UXMapBundle.php:90]: Not a big fan of variables in service names (just personal taste here)

File: src/Map/src/Renderer/AbstractRenderer.php (hunk 5 above)
Comment (Kocal) [reply src/Map/src/Renderer/AbstractRenderer.php:54]: Inspired from https://laravel.com/docs/11.x/helpers#method-tap, this idea is to:
- accept a parameter
- do something to this parameter
- return the parameter

File: src/Map/src/UXMapBundle.php (hunk 6 above)
Comment (Kocal) [reply src/Map/src/UXMapBundle.php:52]: Do you mean something like:
```yaml
ux_map:
    default_options:
        mapId: 1234 # or map_id: 1234
```

?

Comment (Kocal) [reply src/Map/src/UXMapBundle.php:52]: (I'm waiting for a response before applying your other comments or not, since they will invalidated by your first message here)

File: src/Map/src/Bridge/Google/src/GoogleOptions.php (hunk 1 above)
Comment (Kocal) [reply src/Map/src/Bridge/Google/src/GoogleOptions.php:52]: Alright

Comment (Kocal) [reply src/Map/src/Bridge/Google/src/GoogleOptions.php:52]: (yeah I felt the same when I saw the migration from `KernelTestCase::$container` to `KernelTestCase::getContainer()` :p)

File: src/Map/src/UXMapBundle.php (hunk 6 above)
Comment (smnandre) [reply src/Map/src/UXMapBundle.php:52]: Let's merge this one i'll talk tou you later ;)

**Review by smnandre — APPROVED** [review]

File: src/Map/src/Bridge/Google/tests/GoogleRendererTest.php [hunk 8]
```diff
@@ -78,5 +78,23 @@ public function provideTestRenderMap(): iterable
...
+            'renderer' => new GoogleRenderer(new StimulusHelper(null), 'my_api_key', defaultMapId: 'DefaultMapId'),
+            'map' => (clone $map),
+        ];
+        yield 'with default map id, when passing options (except the "mapId")' => [
+            'expected_renderer' => '<div data-controller="symfony--ux-google-map--map" data-symfony--ux-google-map--map-provider-options-value="{&quot;apiKey&quot;:&quot;my_api_key&quot;}" data-symfony--ux-google-map--map-view-value="{&quot;center&quot;:{&quot;lat&quot;:48.8566,&quot;lng&quot;:2.3522},&quot;zoom&quot;:12,&quot;fitBoundsToMarkers&quot;:false,&quot;options&quot;:{&quot;mapId&quot;:DefaultMapId,&quot;gestureHandling&quot;:&quot;auto&quot;,&quot;backgroundColor&quot;:null,&quot;disableDoubleClickZoom&quot;:false,&quot;zoomControlOptions&quot;:{&quot;position&quot;:22},&quot;mapTypeControlOptions&quot;:{&quot;mapTypeIds&quot;:[],&quot;position&quot;:14,&quot;style&quot;:0},&quot;streetViewControlOptions&quot;:{&quot;position&quot;:22},&quot;fullscreenControlOptions&quot;:{&quot;position&quot;:20}},&quot;markers&quot;:[],&quot;polygons&quot;:[]}"></div>',
```
Comment (smnandre) [inline src/Map/src/Bridge/Google/tests/GoogleRendererTest.php]:
```suggestion
            'expected_renderer' => '<div data-controller="symfony--ux-google-map--map" data-symfony--ux-google-map--map-provider-options-value="{&quot;apiKey&quot;:&quot;my_api_key&quot;}" data-symfony--ux-google-map--map-view-value="{&quot;center&quot;:{&quot;lat&quot;:48.8566,&quot;lng&quot;:2.3522},&quot;zoom&quot;:12,&quot;fitBoundsToMarkers&quot;:false,&quot;options&quot;:{&quot;mapId&quot;:&quot;DefaultMapId&quot;,&quot;gestureHandling&quot;:&quot;auto&quot;,&quot;backgroundColor&quot;:null,&quot;disableDoubleClickZoom&quot;:false,&quot;zoomControlOptions&quot;:{&quot;position&quot;:22},&quot;mapTypeControlOptions&quot;:{&quot;mapTypeIds&quot;:[],&quot;position&quot;:14,&quot;style&quot;:0},&quot;streetViewControlOptions&quot;:{&quot;position&quot;:22},&quot;fullscreenControlOptions&quot;:{&quot;position&quot;:20}},&quot;markers&quot;:[],&quot;polygons&quot;:[]}"></div>',
```

Comment (smnandre) [reply src/Map/src/Bridge/Google/tests/GoogleRendererTest.php]: Seems to be the cause of the failing checks

Comment (Kocal) [reply src/Map/src/Bridge/Google/tests/GoogleRendererTest.php]: Yes IK, I didn't have time to continue

Comment (smnandre) [reply src/Map/src/Bridge/Google/tests/GoogleRendererTest.php]: Just wanted to help 😅

Comment (Kocal) [reply src/Map/src/Bridge/Google/tests/GoogleRendererTest.php]: tumblr_b9bf67bfbbb64aff6f404e4dabd5f80a_f38f5521_540

🤭

Comment (Kocal) [reply src/Map/src/Bridge/Google/tests/GoogleRendererTest.php]: But yeah that's was it! This issue was different from the local issue because the Google bridge had dependency on UX Map from packagist (without the `tapOptions` thing). A symbolic link and applying your patch fixed the issue.
