### PR TITLE
[Live] Lower the normalizer priority of `DoctrineObjectNormalizer` and fix embeddables

### LINKED ISSUE #452: [Live Component] DoctrineObjectNormalizer is being used to normalize my non-Doctrine object
Using v2.3 of the Live Component.

I'm using a DTO as a data class with a form in a live component. It's working OK with scalar values in the DTO.

However, when I try and use `Money/Money` object as one of the form data properties, it borks with:

```
ErrorException:
Warning: Undefined array key 0

  at vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php:883
  at Doctrine\ORM\Mapping\ClassMetadataInfo->getIdentifierValues(object(Money))
     (vendor/symfony/ux-live-component/src/Normalizer/DoctrineObjectNormalizer.php:44)
  at Symfony\UX\LiveComponent\Normalizer\DoctrineObjectNormalizer->normalize(object(Money), 'json', array('live-component' => true, 'cache_key' => '87beb01efbb89bc8a83bf4e8e91ba0dc', 'circular_reference_limit_counters' => array('0000000000000d700000000000000000' => 1)))
     (vendor/symfony/serializer/Serializer.php:161)
  at Symfony\Component\Serializer\Serializer->normalize(object(Money), 'json', array('live-component' => true, 'cache_key' => '87beb01efbb89bc8a83bf4e8e91ba0dc', 'circular_reference_limit_counters' => array('0000000000000d700000000000000000' => 1)))
     (vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:216)
  at Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->normalize(object(DefaultPriceData), 'json', array('live-component' => true, 'cache_key' => '87beb01efbb89bc8a83bf4e8e91ba0dc', 'circular_reference_limit_counters' => array('0000000000000d700000000000000000' => 1)))
     (vendor/symfony/serializer/Serializer.php:161)
  at Symfony\Component\Serializer\Serializer->normalize(object(DefaultPriceData), 'json', array('live-component' => true))
     (vendor/symfony/ux-live-component/src/LiveComponentHydrator.php:87)file=vendor/symfony/serializer/Serializer.php&line=161#line161)-> normalize (line 161)
```

Looking at the `DoctrineObjectNormalizer` I see it is given a priority of 100, making it kick in way before my custom Money normalizer which is already registered with the serializer.

Why is the `DoctrineObjectNormalizer` given such a high priority, and why is it trying to normalize my non-Doctrine object?

What would be the best way to get around this?

Thank you.

### PR DESCRIPTION
**Pull request by kbond**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| Tickets       | Fix #452
| License       | MIT

Changed from 100 to -100, we want a user's entity normalizers to run before. We also want `DoctrineObjectNormalizer` to run before the default object normalizer.

Tests added to cover the following ways object properties on a component are normalized:
- entity with no custom normalizer (uses `DoctrineObjectNormalizer`)
- entity with custom normalizer
- dto with custom normalizer
- dto with no custom normalizer (uses the default object normalizer)
- entity with embeddable (mapped using annotations)
- entity with embeddable (mapped using xml)
- dto with embeddable (mapped using annotations)
- dto with embeddable (mapped using xml)

### CODE REVIEW

File: src/LiveComponent/src/Normalizer/DoctrineObjectNormalizer.php [hunk 1]
```diff
@@ -83,10 +84,29 @@ private function objectManagerFor(string $class): ?ObjectManager
...
             }
         }
 
         return null;
     }
+
+    /**
+     * Ensure the $class is not embedded or a mapped superclass.
+     */
+    private static function ensureManagedObject(ObjectManager $om, string $class): ?ObjectManager
```
Comment (kbond) [inline src/LiveComponent/src/Normalizer/DoctrineObjectNormalizer.php:97]: See https://github.com/symfony/ux/issues/452#issuecomment-1242154695 for why this is needed.

**Comment by weaverryan** [comment]
Thanks Kevin!

**Comment by benr77** [comment]
Yes - thanks for your efforts Kevin.

@weaverryan Do you know when you are likely to tag a release with these changes? Thanks.

**Comment by weaverryan** [comment]
Not sure - maybe a week or two - I have some other changes I'd like to get in first - but typically we're releasing monthly, and it's nearly been a month.
