### PR TITLE
[Icons] Fix `aliases` and `default_attributes` config types for `config/reference.php`

### LINKED ISSUE #3193: [Icons] `config/recerence.php` ux_icons.aliases wrong type
Not sure to report here or to Symfony repo.

`reference.php` introduced in Symfony 7.4 contains wrong type for `aliases` config.
```php
/**
 * @psalm-type UxIconsConfig = array{
 *     icon_dir?: scalar|null, // The local directory where icons are stored. // Default: "%kernel.project_dir%/assets/icons"
 *     default_icon_attributes?: mixed, // Default attributes to add to all icons. // Default: {"fill":"currentColor"}
 *     icon_sets?: array<string, array{ // the icon set prefix (e.g. "acme") // Default: []
 *         path?: scalar|null, // The local icon set directory path. (cannot be used with 'alias')
 *         alias?: scalar|null, // The remote icon set identifier. (cannot be used with 'path')
 *         icon_attributes?: list<mixed>,
 *     }>,
 *     aliases?: list<scalar|null>, <-- THIS LINE HERE
 *     iconify?: bool|array{ // Configuration for the remote icon service.
 *         enabled?: bool, // Default: true
 *         on_demand?: bool, // Whether to download icons "on demand". // Default: true
 *         endpoint?: scalar|null, // The endpoint for the Iconify icons API. // Default: "https://api.iconify.design"
 *     },
 *     ignore_not_found?: bool, // Ignore error when an icon is not found. Set to 'true' to fail silently. // Default: false
 * }
 */
```
By the info and example (`symfony console config:dump-reference ux_icons`), it should be `array<string, string>`.
```yaml
ux_icons:
    # Icon aliases (map of alias => full name).
    aliases:              []

        # Examples:
        # dots:                'clarity:ellipsis-horizontal-line'
        # privacy:             'bi:cookie'
```

### PR DESCRIPTION
**Pull request by Kocal**
| Q              | A
| -------------- | ---
| Bug fix?       | yes
| New feature?   | no 
| Deprecations?  | no 
| Documentation? | no 
| Issues         | Fix #3193 
| License        | MIT

Types are now correct:
image

### CODE REVIEW

File: src/Icons/src/DependencyInjection/UXIconsExtension.php [hunk 1]
```diff
@@ -63,7 +64,9 @@ public function getConfigTreeBuilder(): TreeBuilder
                                 ->info('Override default icon attributes for icons in this set.')
                                 ->example(['class' => 'icon icon-acme', 'fill' => 'none'])
                                 ->normalizeKeys(false)
-                                ->variablePrototype()
+                                ->useAttributeAsKey('key')
+                                ->{method_exists(ArrayNodeDefinition::class, 'stringPrototype') ? 'stringPrototype' : 'scalarPrototype'}()
```
Comment (Kocal) [inline src/Icons/src/DependencyInjection/UXIconsExtension.php]: 💡  `ArrayNodeDefinition::stringPrototype()` has been added on 7.2
