### PR TITLE
[LiveComponent] Remove CSRF tokens - rely on same-origin/CORS instead

### LINKED ISSUE #2177: [LiveComponent] Testing forms causes exeption "There is currently no session available."
I'm trying to test my live component which contains a form. The following code raises an exception of type `Symfony\Component\HttpFoundation\Exception\SessionNotFoundException`.

My sample testcode:
```
$formComponent = $this->createLiveComponent(
        name: ProductionForm::class,
)->actingAs($testUser);

$formComponent->set('form_name.title', 'Loreum Ipsum');
```

The user and the field exist. What else is needed to get the test working?

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | could be
| Issues        | Fixes https://github.com/symfony/ux/issues/2177
| License       | MIT

This PR replaces token-based CSRF-protection by same-origin/CORS policies.
It replaces #2250

### CODE REVIEW

File: src/LiveComponent/src/DependencyInjection/Compiler/OptionalDependencyPass.php [hunk 1]
```diff
@@ -33,5 +33,10 @@ public function process(ContainerBuilder $container): void
                 ->addTag(LiveComponentBundle::HYDRATION_EXTENSION_TAG)
             ;
         }
+
+        if (!$container->hasDefinition('test.client')) {
+            $container->getDefinition('ux.live_component.event_subscriber')
+                ->setArgument(1, false);
```
Comment (nicolas-grekas) [inline src/LiveComponent/src/DependencyInjection/Compiler/OptionalDependencyPass.php:39]: In test mode, we don't require the custom `Accept` content-type to make testing easier (and not break existing tests).

File: src/LiveComponent/src/EventListener/LiveComponentSubscriber.php [hunk 2]
```diff
@@ -344,7 +337,17 @@ private function createResponse(MountedComponent $mounted): Response
...
+            return false;
+        }
+
+        if ($this->testMode) {
+            return true;
+        }
+
+        // Except when testing, require the correct content-type in the Accept header.
+        // This also acts as a CSRF protection since this can only be set in accordance with same-origin/CORS policies.
+        return \in_array(self::HTML_CONTENT_TYPE, $request->getAcceptableContentTypes(), true);
```
Comment (nicolas-grekas) [inline src/LiveComponent/src/EventListener/LiveComponentSubscriber.php:348]: This is the most important part of this PR: we mandate our custom content-type in the `Accept` header.

File: src/LiveComponent/src/EventListener/LiveComponentSubscriber.php [hunk 3]
```diff
@@ -344,7 +335,17 @@ private function createResponse(MountedComponent $mounted): Response
...
     private function isLiveComponentRequest(Request $request): bool
     {
-        return $request->attributes->has('_live_component');
+        if (!$request->attributes->has('_live_component')) {
+            return false;
+        }
+
+        if ($this->testMode) {
+            return true;
+        }
```
Comment (smnandre) [inline src/LiveComponent/src/EventListener/LiveComponentSubscriber.php:344]: This feels a bit weird to have this here... don't you think ?

File: src/LiveComponent/src/Attribute/AsLiveComponent.php [hunk 4]
```diff
@@ -24,33 +24,62 @@
...
+
+            switch (\func_num_args()) {
+                case 6: $route = 'ux_live_component';
+                    // no break
+                case 7: $method = 'post';
+                    // no break
+                case 8: $urlReferenceType = UrlGeneratorInterface::ABSOLUTE_PATH;
+                    // no break
+                default:
+            }
```
Comment (smnandre) [inline src/LiveComponent/src/Attribute/AsLiveComponent.php:71]: Nice

File: src/LiveComponent/src/EventListener/LiveComponentSubscriber.php (hunk 2 above)
Comment (smnandre) [reply src/LiveComponent/src/EventListener/LiveComponentSubscriber.php:348]: Could we refactor in a way we test this only once per request ?

**Comment by onEXHovia** [comment]
Many developers, for various reasons(anwser stackoverflow), can add `Access-Control-Allow-Origin: * ` header for all requests its loosens Single Origin Policy (SOP) and allows you to execute request using `XMLHttpRequest `  and setting `Accept` header. Classic way with hidden input, seems like more effective or at least an additional layer against CSRF.

File: src/LiveComponent/src/EventListener/LiveComponentSubscriber.php (hunk 2 above)
Comment (nicolas-grekas) [reply src/LiveComponent/src/EventListener/LiveComponentSubscriber.php:348]: I'm not sure it's worth it: the way to do that would be to use an attribute on the request object, polluting the list of attributes. The check should be fast enough and rare enough.

File: src/LiveComponent/src/EventListener/LiveComponentSubscriber.php (hunk 3 above)
Comment (nicolas-grekas) [reply src/LiveComponent/src/EventListener/LiveComponentSubscriber.php:344]: I don't :) It's the way to make the new behavior seamless for existing test suites. The alternative (requiring test cases to all add HTTP_ACCEPT to their calls) looks like forcing boilerplate.

**Comment by nicolas-grekas** [comment]
@onEXHovia thanks for the comment but I'm not sure what you're suggesting for this PR?

File: src/LiveComponent/src/EventListener/LiveComponentSubscriber.php (hunk 3 above)
Comment (smnandre) [reply src/LiveComponent/src/EventListener/LiveComponentSubscriber.php:344]: In general, not a big fan of having test-or-dev code in the final classes. 

To be honest, I had the _feeling_ this was one of the "untold conventions" in the symfony codebase.. but if you're good with it, i'm good with it :)

Comment (smnandre) [reply src/LiveComponent/src/EventListener/LiveComponentSubscriber.php:344]: Suggestion here, what about renaming something like "controlHeader" or even "acceptHeader" instead ? And set it's default value to "true", instead of having a "false" in the constructor ?

File: src/Autocomplete/composer.json [hunk 5]
```diff
@@ -45,7 +45,6 @@
         "symfony/phpunit-bridge": "^6.3|^7.0",
         "symfony/process": "^6.3|^7.0",
         "symfony/security-bundle": "^6.3|^7.0",
-        "symfony/security-csrf": "^6.3|^7.0",
```
Comment (smnandre) [inline src/Autocomplete/composer.json]: Good catch! Ok for you if i extract this in another PR ?

Comment (smnandre) [reply src/Autocomplete/composer.json]: --> https://github.com/symfony/ux/pull/2264

**Comment by onEXHovia** [comment]
> @onEXHovia thanks for the comment but I'm not sure what you're suggesting for this PR?

If we consider this implementation and current with hidden token, I see two different scenarios. Without documentation developers may not know that live component depends on SOP in js for protections CSRF and added header Access-Control-Allow-Origin could mean potential CSRF.

On the other hand, implementation with token is more explicit. Developer disable it through the component configuration and understands that could mean potential CSRF.

Discussion in #2250 
> Enabling CSRF by default means enabling the session, making requests stateful.

> CSRF protection is not a "feature", nobody is "using it" in the sense that it's a behavior that shouldn't have any visible effect to any normal workflow.

The same can be said about stateless requests, usually no one tries to make all requests stateless. I don't see any reason to remove the token based implementation, as a solution we could add a global configuration that configures the CSRF behavior for all components.

**Review by kbond — APPROVED** [review]
This is really nice! Ryan and I always wanted the possibility for stateless live components but csrf was our Achilles heel!

**Comment by daFish** [comment]
This MR helps with #2177 and fixes the issue. My attempt to fix it in #2254 is no longer needed.

File: src/LiveComponent/src/EventListener/LiveComponentSubscriber.php (hunk 3 above)
Comment (nicolas-grekas) [reply src/LiveComponent/src/EventListener/LiveComponentSubscriber.php:344]: testMode defaults to true... :)

Comment (nicolas-grekas) [reply src/LiveComponent/src/EventListener/LiveComponentSubscriber.php:344]: If you mean changing the default behavior, this makes the tests all red - aka it's a BC break.

**Comment by nicolas-grekas** [comment]
I've just added a note about CSRF / CORS in the doc.

File: src/LiveComponent/src/EventListener/LiveComponentSubscriber.php (hunk 3 above)
Comment (smnandre) [reply src/LiveComponent/src/EventListener/LiveComponentSubscriber.php:344]: 👍

**Review by kbond — APPROVED** [review]

**Comment by smnandre** [comment]
LGTM :) 

@nicolas-grekas can you update the CHANGELOG in the src/LiveComponent repository ?

**Review by smnandre — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
CHANGELOG updated

**Comment by kbond** [comment]
Thank you Nicolas.
