### PR TITLE
[TwigComponent] Fix `loadTemplate` deprecation for Twig >= 3.21

### LINKED ISSUE #2710: ComponentNode uses $this->loadTemplate which is deprecated in Twig 3.20.0
See https://github.com/twigphp/Twig/pull/4583

I believe it should be changed to `load` in 3.20.0

### PR DESCRIPTION
**Pull request by smnandre**
Fix #2710

cf https://github.com/twigphp/Twig/pull/4583

Poke @ruudk

### CODE REVIEW

**Comment by Kocal** [comment]
Are failing checks for LiveComponent https://github.com/symfony/ux/actions/runs/14850493570/job/41693042531?pr=2713 are related to your changes?

**Comment by smnandre** [comment]
They are, but because they are hardcoded values.. that is dependending on internal code in TwigComponent.

Let's try to fix this later this week and we will merge this MR then.

File: src/TwigComponent/src/Twig/ComponentNode.php [hunk 1]
```diff
@@ -154,16 +154,29 @@ public function compile(Compiler $compiler): void
...
+            $compiler
+               ->write('$this->load(')
+               ->string($this->getAttribute('embedded_template'))
+               ->raw(', ')
+               ->repr($this->getTemplateLine())
+               ->raw(', ')
+               ->string($this->getAttribute('embedded_index'))
+               ->raw(')');
+        } else {
+            // @deprecated since Twig 3.20
```
Comment (stof) [inline src/TwigComponent/src/Twig/ComponentNode.php]: Either the comment should say `deprecated since Twig 3.21` (or `compat for Twig <= 3.20 instead), or the version_id check is using the wrong version.

**Comment by Kocal** [comment]
I wasn't able to locally reproduce the errors from CI https://github.com/symfony/ux/actions/runs/15055025384/job/42318841525?pr=2713
```
1) Symfony\UX\LiveComponent\Tests\Integration\EventListener\DataModelPropsSubscriberTest::testDataModelPropsAreAvailableInEmbeddedComponents
Twig\Error\RuntimeError: An exception has been thrown during the rendering of a template ("Call to undefined method __TwigTemplate_18a043059dae08abfc5bc95f85ec1668::load()").

/home/runner/work/ux/ux/src/LiveComponent/tests/Fixtures/templates/components/parent_component_data_model.html.twig:1
/home/runner/work/ux/ux/src/LiveComponent/vendor/twig/twig/src/Template.php:354
/home/runner/work/ux/ux/src/LiveComponent/vendor/twig/twig/src/Template.php:369
/home/runner/work/ux/ux/src/TwigComponent/src/ComponentRenderer.php:77
/home/runner/work/ux/ux/src/TwigComponent/src/ComponentRenderer.php:56
/home/runner/work/ux/ux/src/LiveComponent/tests/Integration/EventListener/DataModelPropsSubscriberTest.php:52
```

I've changed the condition to `method_exists` and tests are passing again https://github.com/symfony/ux/actions/runs/15055235144/job/42319532430?pr=2713

**Review by kbond — APPROVED** [review]

File: src/TwigComponent/CHANGELOG.md [hunk 2]
```diff
@@ -1,5 +1,9 @@
 # CHANGELOG
 
+## 2.25.0
+
+-  Fix `Template#loadTemplate` deprecation for Twig >=3.21
```
Comment (smnandre) [inline src/TwigComponent/CHANGELOG.md]: Not something that user should be noticed in the Changelog imho

**Comment by smnandre** [comment]
Let's not force-push / squash on previous commits when working on same PR, because that's hard to review then 😅

File: src/TwigComponent/CHANGELOG.md (hunk 2 above)
Comment (Kocal) [reply src/TwigComponent/CHANGELOG.md]: Ah? I believe people will be happy to know the deprecation is fixed:
> as we are getting more and more complaints in support channels about Symfony triggering Twig deprecations

More generally, I don't like not seeing a changelog entry when a package tags a new version. I don't know what's been changed, and it may look suspicious. 

Maybe the actual entry is too technical? What about "Fix deprecations with Twig >= 3.21"?

Comment (smnandre) [reply src/TwigComponent/CHANGELOG.md]: That's not the same as the changelog we publish / visible on the website.

I think the Symfony standard is to only write what can change / been used by the user (new features mainly) 

(imagine a changelog with all the bug fixes, you don't see anything anymore)

Comment (Kocal) [reply src/TwigComponent/CHANGELOG.md]: I've just looked at ~10 random fixes PR on symfony/symfony, and indeed none of them updated the changelog.

I will remove the entry then :)

**Comment by Kocal** [comment]
Thanks Simon.

File: src/TwigComponent/CHANGELOG.md (hunk 2 above)
Comment (kbond) [reply src/TwigComponent/CHANGELOG.md]: This'll be in the release notes
