### PR TITLE
[LiveComponent] Fix `#[LiveProp(writable: true, url: true)]` that was not updated as a query parameter

### LINKED ISSUE #2960: [LiveComponent] 500 errors with MethodNotAllowedException on dev after 2.28 upgrade
Hello,

After upgrading UX Live component from 2.27 to 2.28.1 (but the bug also happens on 2.28.0), I'm getting the following error when I toggle some checkboxes that are marked as `#[LiveProp(writable: true)]` in the related Live component.

After having a little look at the merged PRs between the releases, I guess this is the one making it fail now: https://github.com/symfony/ux/pull/2673

Here's the stack trace:

```
Symfony\Component\Routing\Exception\MethodNotAllowedException:

  at vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:42
  at Symfony\Component\Routing\Matcher\CompiledUrlMatcher->match()
     (vendor/symfony/routing/Router.php:177)
  at Symfony\Component\Routing\Router->match()
     (vendor/symfony/ux-live-component/src/Util/UrlFactory.php:63)
  at Symfony\UX\LiveComponent\Util\UrlFactory->createPath()
     (vendor/symfony/ux-live-component/src/Util/UrlFactory.php:45)
  at Symfony\UX\LiveComponent\Util\UrlFactory->createFromPreviousAndProps()
     (vendor/symfony/ux-live-component/src/EventListener/LiveUrlSubscriber.php:48)
  at Symfony\UX\LiveComponent\EventListener\LiveUrlSubscriber->onKernelResponse()
     (vendor/symfony/event-dispatcher/Debug/WrappedListener.php:115)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke()
     (vendor/symfony/event-dispatcher/EventDispatcher.php:206)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
     (vendor/symfony/event-dispatcher/EventDispatcher.php:56)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
     (vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:126)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch()
     (vendor/symfony/http-kernel/HttpKernel.php:216)
  at Symfony\Component\HttpKernel\HttpKernel->filterResponse()
     (vendor/symfony/http-kernel/HttpKernel.php:204)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:76)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:182)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php:35)
  at Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
     (vendor/autoload_runtime.php:29)
  at require_once('/.../vendor/autoload_runtime.php')
     (public/index.php:7)               
```

I'll try to create a reproducer soon.

### LINKED ISSUE #2975: Upgrade to 2.28 breaks live-props as url
Hi guys, I found a problem when upgrading `symfony/ux-live-component` from 2.27 to 2.28: I have a live-prop with url true, like this:

    #[LiveProp(writable: true, url: true)]
    public int $page=1;

In 2.27 the page-parameter is in the url and gets updated when the property changes. In 2.28 the page-parameter isn't added to the url, even when the value changes. Maybe it is related to the change in UrlMapping.

### PR DESCRIPTION
**Pull request by mbuliard**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| Docs?         | no
| Issues        | Fix #2960 Fix #2975
| License       | MIT

Follows https://github.com/symfony/ux/pull/2673

Hi,
The LiveUrl feature in 2.28 introduced a few bugs and I would like to fix some :

* The symfony matcher uses the current method to find the route. The UrlFactory must temporarily replace it by a GET. Will fix the MethodNotAllowedException bug of #2960 #2975 
* The symfony matcher should not be given the query, only the path.

### CODE REVIEW

File: src/LiveComponent/src/Util/UrlFactory.php [hunk 1]
```diff
@@ -60,10 +54,24 @@ public function createFromPreviousAndProps(
...
+    }
+
+    private function matchRoute(string $previousUrl): string
+    {
+        $context = $this->router->getContext();
+        $tmpContext = clone $context;
+        $tmpContext->setMethod('GET');
+        $this->router->setContext($tmpContext);
+        $match = $this->router->match($previousUrl);
+        $this->router->setContext($context);
```
Comment (Kocal) [inline src/LiveComponent/src/Util/UrlFactory.php]: So the previous context can be re-set correctly:
```suggestion
        $context = $this->router->getContext();
        $tmpContext = clone $context;
        $tmpContext->setMethod('GET');
        $this->router->setContext($tmpContext);
        try {
            $match = $this->router->match($previousUrl);
        } finally {
            $this->router->setContext($context);
        }
```

**Review by Kocal — APPROVED** [review]
Thanks for working on this, that's much appreciated! :) 

Is the modified test enough to cover issue https://github.com/symfony/ux/issues/2975, or should we add a dedicated one?

Also please, can you update your PR's title to something more relevant? Thanks!

**Comment by mbuliard** [comment]
> Thanks for working on this, that's much appreciated! :)
> 
> Is the modified test enough to cover issue #2975, or should we add a dedicated one?
> 
> Also please, can you update your PR's title to something more relevant? Thanks!

@Kocal 
I would have prefered to help for the fixes sooner but I was on vacation, without computer. :-/

I edited the fixtures of functional tests to reproduce the bug. Previously the route was accepting all methods and the problem was not detected.

I am confident that the issue #2975 is the same as the previous #2960 but the exception is caught by the hotfix #2961 and no new url is returned.

**Comment by Kocal** [comment]
So should we remove the `MethodNotAllowedException` from `catch()`?

**Comment by mbuliard** [comment]
> So should we remove the `MethodNotAllowedException` from `catch()`?

I think the exception should not happen, but since the `$previousUrl` comes from user-land, anything can enter, including a url matching a POST route, which would throw the exception. I would keep catching it, just in case.

**Comment by Kocal** [comment]
I confirm it fixes #2975, thanks!

**Comment by Kocal** [comment]
Thank you @mbuliard.
