### PR TITLE
[TwigComponent] Fix ComponentTokenParser on 32-bits

### LINKED ISSUE #2568: [TwigComponent] ComponentTokenParser failing to generate template index on 32bit platform
This issue affects **only 32bit** platforms. 

Appending digits to a 32bit integer in [ComponentTokenParser::generateEmbeddedTemplateIndex](https://github.com/symfony/ux/blob/63c88090dcac127e1263bfa5d9e43894ac312a95/src/TwigComponent/src/Twig/ComponentTokenParser.php#L121) is prone to integer overflows on 32bit systems, resulting in errors like:

> Symfony\UX\TwigComponent\Twig\ComponentTokenParser::generateEmbeddedTemplateIndex(): Return value must be of type int, string returned 

I guess, that’s what happened in https://github.com/EasyCorp/EasyAdminBundle/issues/6713

Furthermore, `crc32` itself [can return negative integers](https://www.php.net/manual/en/function.crc32.php#:~:text=many%20crc32%20checksums%20will%20result%20in%20negative%20integers%20on%2032bit%20platforms) on 32bit which can lead to unexpected results (`-` in [compiled class names](https://github.com/twigphp/Twig/blob/f1c9039106ecc5a8182e1536027a6940ac4a8ab8/src/Node/ModuleNode.php#L183)).

### PR DESCRIPTION
**Pull request by smnandre**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| Issues        | Fix #2568
| License       | MIT

- 64-bit users get the original behavior
- 32-bit users get the fix to prevent overflow issues

### CODE REVIEW

File: src/TwigComponent/src/Twig/ComponentTokenParser.php [hunk 1]
```diff
@@ -118,6 +118,14 @@ private function generateEmbeddedTemplateIndex(string $file, int $line): int
             $this->lineAndFileCounts[$fileAndLine] = 0;
         }
 
-        return crc32($fileAndLine).++$this->lineAndFileCounts[$fileAndLine];
+        $index = crc32($fileAndLine).++$this->lineAndFileCounts[$fileAndLine];
+
+        if (4 === \PHP_INT_SIZE) {
+            // On 32-bit PHP, the index can be negative
+            // we need to convert it to a positive integer
+            $index = abs($index) % \PHP_INT_MAX + 1;
```
Comment (smnscp) [inline src/TwigComponent/src/Twig/ComponentTokenParser.php]:
```suggestion
            // On 32-bit PHP, the index can be negative or greater than PHP_INT_MAX
            // we need to convert it to a positive 32-bit integer
            $index = fmod(abs($index), \PHP_INT_MAX) + 1;
```
Using `fmod` here instead of the modulo operator is important, because `abs($index)` might return a float greater than `PHP_INT_MAX`, which `%` would [convert to a negative integer](https://www.php.net/manual/en/language.operators.arithmetic.php#:~:text=Operands%20of%20modulo%20are%20converted%20to%20int), resulting [in a negative](https://www.php.net/manual/en/language.operators.arithmetic.php#:~:text=has%20the%20same%20sign%20as%20the%20dividend) remainder.

**Review by smnscp — CHANGES_REQUESTED** [review]
Hi @smnandre, I tested the patch on a 32-bit system. Unfortunately, `console clear:cache` failed again with:
> syntax error, unexpected token "-", expecting "{"

That’s due to a compiled template component class with a `-` in the class name.
My suggestion solves this problem.

File: src/TwigComponent/src/Twig/ComponentTokenParser.php (hunk 1 above)
Comment (smnscp) [reply src/TwigComponent/src/Twig/ComponentTokenParser.php]: FWIW, we could add explicit integer conversion to that line to spare confusion. Up to you.

**Comment by smnandre** [comment]
> Hi @smnandre, I tested the patch on a 32-bit system. Unfortunately, `console clear:cache` failed again with:
> 
> > syntax error, unexpected token "-", expecting "{"
> 
> That’s due to a compiled template component class with a `-` in the class name. My suggestion solves this problem.

Thanks a lot! I've commited your suggested code. Tell me if this is ok for you and LGTM :)

**Review by smnscp — APPROVED** [review]
LGTM. Thanks!

**Comment by smnandre** [comment]
Note: test failures are related to deprecations in Twig, that will require a dedicated PR

**Review by Kocal — APPROVED** [review]
