### PR TITLE
[LiveComponent] Fix BC break when using `PropertyTypeExtractorInterface::getType()` on a `#[LiveProp]` property `x` when getter `getX` exists

### LINKED ISSUE #2888: BC break in LiveComponentHydrator
There is a BC break in LiveComponentHydrator as it now throws an exception when dehydrating a User entity class extending UserInterface. 

Image

Image

In `\Symfony\UX\LiveComponent\LiveComponentHydrator::dehydrateObjectValue` the `$classType` parameter value is the interface not the class as it was before (in `LegacyLivePropMetadata`).

The component looks like this:

```php
<?php

declare(strict_types=1);

namespace App\Component;

use App\Controller\BaseController;
use App\Entity\User;
use App\Form\Type\UserAdminType;
use Symfony\Component\Form\FormInterface;
use Symfony\UX\LiveComponent\Attribute\AsLiveComponent;
use Symfony\UX\LiveComponent\Attribute\LiveProp;
use Symfony\UX\LiveComponent\ComponentWithFormTrait;
use Symfony\UX\LiveComponent\DefaultActionTrait;

#[AsLiveComponent('user_admin_form')]
final class UserAdminForm extends BaseController
{
    use DefaultActionTrait;
    use ComponentWithFormTrait;

    #[LiveProp]
    public User $user;

    protected function instantiateForm(): FormInterface
    {
        return $this->createForm(UserAdminType::class, $this->user, ['is_edit' => true]);
    }
}

```

### PR DESCRIPTION
**Pull request by Kocal**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no 
| Docs?         | no 
| Issues        | Fix #2888 
| License       | MIT

Prevent:
```
1) Symfony\UX\LiveComponent\Tests\Functional\Form\ComponentWithFormTest::testFormWithLivePropContainingAnEntityImplementingAnInterface
LogicException: Cannot dehydrate value typed as interface "Symfony\UX\LiveComponent\Tests\Fixtures\Entity\User" on component "Symfony\UX\LiveComponent\Tests\Fixtures\Component\FormWithUserInterfaceComponent". Change this to a concrete type that can be dehydrated. Or set the hydrateWith/dehydrateWith options in LiveProp or set "useSerializerForHydration: true" on the LiveProp to use the serializer.
```

Given the LiveComponent:
```php
<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Symfony\UX\LiveComponent\Tests\Fixtures\Component;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormInterface;
use Symfony\UX\LiveComponent\Attribute\AsLiveComponent;
use Symfony\UX\LiveComponent\Attribute\LiveProp;
use Symfony\UX\LiveComponent\ComponentWithFormTrait;
use Symfony\UX\LiveComponent\DefaultActionTrait;
use Symfony\UX\LiveComponent\Tests\Fixtures\Entity\User;
use Symfony\UX\LiveComponent\Tests\Fixtures\Form\UserFormType;

#[AsLiveComponent('form_with_user_interface', template: 'components/form_with_user_interface.html.twig')]
class FormWithUserInterfaceComponent extends AbstractController
{
    use ComponentWithFormTrait;
    use DefaultActionTrait;

    #[LiveProp]
    public User $user;

    protected function instantiateForm(): FormInterface
    {
        return $this->createForm(UserFormType::class, $this->user);
    }
}

```

Dumping `$propMetadata` in `\Symfony\UX\LiveComponent\LiveComponentHydrator::dehydrateValue` gives: 
```
Symfony\UX\LiveComponent\Metadata\LivePropMetadata {#240
  -name: "user"
  -liveProp: Symfony\UX\LiveComponent\Attribute\LiveProp {#230
    -writable: false
    -hydrateWith: null
    -dehydrateWith: null
    -useSerializerForHydration: false
    -serializationContext: []
    -fieldName: null
    -format: null
    -updateFromParent: false
    -onUpdated: null
    -url: false
    -modifier: null
  }
  -type: Symfony\Component\TypeInfo\Type\NullableType {#4197
    -types: array:2 [
      0 => Symfony\Component\TypeInfo\Type\ObjectType {#5811
        -className: "Symfony\Component\Security\Core\User\UserInterface"
      }
      1 => Symfony\Component\TypeInfo\Type\BuiltinType {#4208
        -typeIdentifier: Symfony\Component\TypeInfo\TypeIdentifier {#5983
          +name: "NULL"
          +value: "null"
        }
      }
    ]
    -type: Symfony\Component\TypeInfo\Type\ObjectType {#5811}
  }
}
```

The class name is the `UserInterface` and not `User` 🤔 

## To tests it

- With PropertyInfo only: `sfcp req symfony/property-info:^6.4 -W && sfp vendor/bin/simple-phpunit tests/Functional/Form/ComponentWithFormTest.php --filter "testFormWithLivePropContainingAnEntityImplementingAnInterface"`
- With PropertyInfo & Type: `sfcp req 'symfony/property-info:7.2.*' 'symfony/type-info:7.2.*' && sfp vendor/bin/simple-phpunit tests/Functional/Form/ComponentWithFormTest.php --filter "testFormWithLivePropContainingAnEntityImplementingAnInterface"`

### CODE REVIEW

**Comment by Kocal** [comment]
After some investigations, it happens because of `PhpStanExtractor` from Symfony PropertyInfo.

When trying to resolve the type of `FormWithUserInterfaceComponent::$user`, it will instead resolve the type of `AbstractController::getUser()` which returns `?UserInterface`.

**Comment by Kocal** [comment]
Opened https://github.com/symfony/symfony/issues/61113

**Comment by Kocal** [comment]
After more investigations, I don't think it's related to PropertyInfo itself (PropertyInfo 6.4 also returns type for `AbstractController::getUser()`) but because of the extra logic that use the native `ReflectionType` if possible: 
image

File: src/LiveComponent/src/Metadata/LiveComponentMetadataFactory.php [hunk 1]
```diff
@@ -33,7 +33,11 @@ class LiveComponentMetadataFactory implements ResetInterface
     public function __construct(
         private ComponentFactory $componentFactory,
         private PropertyTypeExtractorInterface $propertyTypeExtractor,
+        private ?TypeResolver $typeResolver = null,
     ) {
+        if (method_exists($this->propertyTypeExtractor, 'getType') && !$this->typeResolver) {
+            throw new \LogicException('Symfony TypeInfo is required to use LiveProps. Try running "composer require symfony/type-info".');
+        }
```
Comment (Kocal) [inline src/LiveComponent/src/Metadata/LiveComponentMetadataFactory.php:40]: Should not happens since `PropertyTypeInfoExtractor::getType()` exists since 7.1, which also ship TypeInfo, but just in case..

File: src/LiveComponent/src/Metadata/LiveComponentMetadataFactory.php [hunk 2]
```diff
@@ -115,10 +119,21 @@ public function createLivePropMetadata(string $className, string $propertyName,
...
+
+            $collectionValueType = $infoType instanceof CollectionType ? $infoType->getCollectionValueType() : null;
+
+            if (null !== $collectionValueType && null !== $infoType) {
+                $type = $infoType;
+            } elseif (null !== $reflectionType) {
+                $type = $this->typeResolver->resolve($reflectionType);
+            } else {
+                $type = Type::mixed();
             }
```
Comment (Kocal) [inline src/LiveComponent/src/Metadata/LiveComponentMetadataFactory.php]: I'm really not sure about this code, it feels fragile.

I tried to re-use the legacy logic and use `ReflectionType` or the result of `PropertyTypeExtractorInterface::getType()`, and now all tests pass, even the one added in this PR (which was previously breaking)

**Review by smnandre — APPROVED** [review]

File: src/LiveComponent/src/Metadata/LiveComponentMetadataFactory.php [hunk 3]
```diff
@@ -115,10 +119,16 @@ public function createLivePropMetadata(string $className, string $propertyName,
...
             );
         } else {
-            $type = $this->propertyTypeExtractor->getType($className, $property->getName());
+            $infoType = $this->propertyTypeExtractor->getType($className, $property->getName());
+
+            $collectionValueType = $infoType instanceof CollectionType ? $infoType->getCollectionValueType() : null;
 
-            if ($type instanceof UnionType && !$type instanceof NullableType || $type instanceof IntersectionType) {
-                throw new \LogicException(\sprintf('Union or intersection types are not supported for LiveProps. You may want to change the type of property "%s" in "%s".', $propertyName, $className));
+            if (null !== $collectionValueType && null !== $infoType) {
```
Comment (mtarld) [inline src/LiveComponent/src/Metadata/LiveComponentMetadataFactory.php]:
```suggestion
            if ($infoType instance of CollectionType) {
```
Seems to be enough no?

Comment (Kocal) [reply src/LiveComponent/src/Metadata/LiveComponentMetadataFactory.php]: I think yes, it would ease the readability too

Comment (Kocal) [reply src/LiveComponent/src/Metadata/LiveComponentMetadataFactory.php]: Applied, thanks

**Comment by Kocal** [comment]
I've added some comments to improve comprehensibility. 

Since the PR fixed the issue from issue's author (https://github.com/symfony/ux/issues/2888#issuecomment-3068613029), and no tests are failing (either when using `PropertyTypeExtractorInterface::getTypes()` or `PropertyTypeExtractorInterface::getType()`), I'm merging.

Thanks both of you :)
