### PR TITLE
[LiveComponent] Fix `ComponentWithFormTrait::extractFormValues()` with edge cases

### LINKED ISSUE #2487: [LiveComponent] Undefined array key "placeholder" after upgrading to 2.22.x
Hello,

recently after upgrading symfony/ux-live-components to 2.22.x I've encountered this exception:

**An exception has been thrown during the rendering of a template ("Warning: Undefined array key "placeholder"").**

Here's the reproducer: https://github.com/maciazek/symfony-ux-live-components-choices-reproducer

I have a custom DatalistType form field, which extends TextType to add HTML datalist into it. Inside DatalistType I'm using 'choices' option to add choices to datalist.
https://github.com/maciazek/symfony-ux-live-components-choices-reproducer/blob/master/src/Form/DatalistType.php#L11-L29
https://github.com/maciazek/symfony-ux-live-components-choices-reproducer/blob/master/templates/form/custom_types.html.twig

I have a form inside live component which is using DatalistType as a child field.
https://github.com/maciazek/symfony-ux-live-components-choices-reproducer/blob/ebe9ff77a7181ed6e0ca4dd5fca7483f38e8ed94/src/Form/ExampleType.php#L9-L30
https://github.com/maciazek/symfony-ux-live-components-choices-reproducer/blob/ebe9ff77a7181ed6e0ca4dd5fca7483f38e8ed94/src/Twig/Components/ExampleForm.php#L13-L23

Everything worked well until updating symfony/ux-live-components to 2.22.x - then I've encountered previously mentioned error.

After some investigation I've found that problem is caused by recent change in ComponentWithFormTrait:
https://github.com/symfony/ux-live-component/blob/5adf780aac0ccbd5cb1dddea683db9aa99b91d4a/src/ComponentWithFormTrait.php#L264-L271

I have 'choices' option in my DatalistType, but it's extending TextType which, as I guess, has no default values for placeholder, multiple and expanded options so they're missing in vars array.

Possible solutions:
1. I can rename option 'choices' to something different, but I still haven't found a better name :)
2. I can set default values for placeholder, multiple and expanded and assign them to vars inside buildView function in my DatalistType - that's my temporary workaround;
3. Maybe these recently added vars tests could be null-coalesced or `array_key_exists`-ed in ComponentWithFormTrait?

Thank you for your great work on the whole UX ecosystem!

### PR DESCRIPTION
**Pull request by smnandre**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no 
| Issues        | Fix #2487 
| License       | MIT

#2403 fixed an old bug to simulate browser behaviour when a select field has no option selected,  no placeholder, and is required (it then uses the first option)
#2425 and #2426 fixed the way we handled empty strings as placeholders

In #2487 @maciazek explained us how a custom type with a "choices" option became unusable since the last changes.

Also.. while I was reading all this I realized we returned wrong values here when "option groups" were used.. leading to other problems.

I updated the code of `extractFormValues()` method to:
* check if most of the caracteristic keys added in `ChoiceType::buildView` were defined in the `$view->vars`, to ensure we are dealing with a `<select>` field built by a `ChoiceType`
* fetch recursively the value of the first displayed option (even with groups)

### CODE REVIEW

**Comment by maciazek** [comment]
I can confirm that this patch resolved my specific case with custom form type and "choices" option. Thank you.

**Comment by norkunas** [comment]
Something is more going on here.
I was getting `An exception has been thrown during the rendering of a template ("Warning: Undefined array key "expanded"").` and so I've tried this patch, then started to get:
`An exception has been thrown during the rendering of a template ("Warning: Undefined array key """).`

While #2490 works for me

**Comment by maciazek** [comment]
> Something is more going on here. I was getting `An exception has been thrown during the rendering of a template ("Warning: Undefined array key "expanded"").` and so I've tried this patch, then started to get: `An exception has been thrown during the rendering of a template ("Warning: Undefined array key """).`
> 
> While #2490 works for me

I think it could happen when form has some ChoiceType field, which has 'choices' set as empty array. In that case
https://github.com/smnandre/ux/blob/cd353fc7a0689b9cee5da252f977acb420176d96/src/LiveComponent/src/ComponentWithFormTrait.php#L269
returns true, and then the error itself comes from:
https://github.com/smnandre/ux/blob/cd353fc7a0689b9cee5da252f977acb420176d96/src/LiveComponent/src/ComponentWithFormTrait.php#L284

Seems that some additional check is needed (if 'choices' is array and if it is not empty?)

**Comment by smnandre** [comment]
Entirely my fault here.

As you can see here i checked for the "choices" existence. 
https://github.com/smnandre/ux/blob/cd353fc7a0689b9cee5da252f977acb420176d96/src/LiveComponent/src/ComponentWithFormTrait.php#L275C33-L275C34

I decided later on to "optimize" and moved the check first, adding an isset in the operation when the key was not defined.... and losing then my original goal: ensure there is one value.

File: src/LiveComponent/src/ComponentWithFormTrait.php [hunk 1]
```diff
@@ -255,25 +256,38 @@ private function extractFormValues(FormView $formView): array
...
-                && (false === $child->vars['placeholder'] || null === $child->vars['placeholder'])
-                && !$child->vars['multiple']
-                && !$child->vars['expanded']
-                && $child->vars['choices']
+            // <select> - Simulate browser behavior
+            // When no option is selected, browsers send the value of the first
+            // option, when the following conditions are met:
+            if (
+                isset($child->vars['choices'])              // has defined choices
+                && $child->vars['required']                 // is required
```
Comment (smnandre) [inline src/LiveComponent/src/ComponentWithFormTrait.php]:
```suggestion
                \array_key_exists('choices', $child->vars)
                && $child->vars['choices']                  // has defined choices  
                && $child->vars['required']                 // is required
```

File: src/LiveComponent/src/ComponentWithFormTrait.php [hunk 2]
```diff
@@ -255,25 +256,39 @@ private function extractFormValues(FormView $formView): array
...
-                && (false === $child->vars['placeholder'] || null === $child->vars['placeholder'])
-                && !$child->vars['multiple']
-                && !$child->vars['expanded']
-                && $child->vars['choices']
+            // <select> - Simulate browser behavior
+            // When no option is selected, browsers send the value of the first
+            // option, when the following conditions are met:
+            if (
+                \array_key_exists('choices', $child->vars)
+                && $child->vars['choices']                  // has defined choices
```
Comment (smnandre) [inline src/LiveComponent/src/ComponentWithFormTrait.php]:
```suggestion
                && $child->vars['choices']                  // has defined choices
```

**Comment by smnandre** [comment]
This should work better now. Thank you very much to both of you.

**Review by Kocal — APPROVED** [review]
