### PR TITLE
[TwigComponent] Fix `ComponentAttributes` rendering when using `StimulusAttributes` as default attributes

### LINKED ISSUE #2756: [Stimulus][TwigComponent] Syntax error escaping objects since 2.25.0
Since 2.25.x using the documented way to merge a stimulus_controller with a twig component attributes results in a javascript syntax error when an object is passed as parameter.

I reproduced this on a new test project, using a simple component with a dummy object like this:
```
<div{{ attributes.defaults(stimulus_controller('test', { myObject: {someProperty: 'test'} })) }}>
    KO: javascript error, unable to parse the myObject attribute
</div>
```

With the stimulus controller waiting an object for "myObject", it gives the following syntax error:
`Uncaught (in promise) SyntaxError: Expected property name or '}' in JSON at position 1 (line 1 column 2)`

It seems that using this syntax to merge the attributes & stimulus_controller escape the stimulus controller attributes in a "bad" way that makes the controller unable to parse it by default.

As a workaround, using toArray on the stimulus_controller result like this seems to work:
```
<div{{ attributes.defaults(stimulus_controller('test', { myObject: {someProperty: 'test'} }).toArray()) }}>
    OK: attributes parsed
</div>
```

### PR DESCRIPTION
**Pull request by Kocal**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no 
| Docs?         | yes 
| Issues        | Fix #2756 
| License       | MIT

We missed the case where we can inject `StimulusAttributes` when using `attributes.defaults()`, as documented in https://symfony.com/bundles/ux-twig-component/current/index.html#component-attributes

It looks like our tests weren't solid enough, since we asserted on `all()` instead of the rendered string.

### CODE REVIEW

File: src/TwigComponent/tests/Unit/ComponentAttributesTest.php [hunk 1]
```diff
@@ -143,16 +143,18 @@ public function testCanAddStimulusControllerViaStimulusAttributes(): void
...
         $attributes = $attributes->defaults($stimulusAttributes);
 
         $this->assertEquals([
             'class' => 'foo',
             'data-controller' => 'foo live',
             'data-live-data-value' => '{}',
             'data-foo-name-value' => 'ryan',
-            'data-foo-some-array-value' => '[&quot;a&quot;,&quot;b&quot;]',
+            'data-foo-some-array-value' => '["a","b"]',
+            'data-foo-some-array-with-keys-value' => '{"key1":"value1","key2":"value2"}'
```
Comment (Kocal) [inline src/TwigComponent/tests/Unit/ComponentAttributesTest.php]: Without the fix:
```
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
     'data-controller' => 'foo live'
     'data-live-data-value' => '{}'
     'data-foo-name-value' => 'ryan'
-    'data-foo-some-array-value' => '["a","b"]'
-    'data-foo-some-array-with-keys-value' => '{"key1":"value1","key2":"value2"}'
+    'data-foo-some-array-value' => '[&quot;a&quot;,&quot;b&quot;]'
+    'data-foo-some-array-with-keys-value' => '{&quot;key1&quot;:&quot;value1&quot;,&quot;key2&quot;:&quot;value2&quot;}'
 )
```

File: src/TwigComponent/tests/Unit/ComponentAttributesTest.php [hunk 2]
```diff
@@ -143,16 +143,18 @@ public function testCanAddStimulusControllerViaStimulusAttributes(): void
...
         ], $attributes->all());
+        $this->assertSame(' data-controller="foo live" data-foo-name-value="ryan" data-foo-some-array-value="[&quot;a&quot;,&quot;b&quot;]" data-foo-some-array-with-keys-value="{&quot;key1&quot;:&quot;value1&quot;,&quot;key2&quot;:&quot;value2&quot;}" class="foo" data-live-data-value="{}"', (string) $attributes);
```
Comment (Kocal) [inline src/TwigComponent/tests/Unit/ComponentAttributesTest.php:157]: Without the fix:
```
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-' data-controller="foo live" data-foo-name-value="ryan" data-foo-some-array-value="[&quot;a&quot;,&quot;b&quot;]" data-foo-some-array-with-keys-value="{&quot;key1&quot;:&quot;value1&quot;,&quot;key2&quot;:&quot;value2&quot;}" class="foo" data-live-data-value="{}"'
+' data-controller="foo live" data-foo-name-value="ryan" data-foo-some-array-value="[&amp;quot;a&amp;quot;,&amp;quot;b&amp;quot;]" data-foo-some-array-with-keys-value="{&amp;quot;key1&amp;quot;:&amp;quot;value1&amp;quot;,&amp;quot;key2&amp;quot;:&amp;quot;value2&amp;quot;}" class="foo" data-live-data-value="{}"'
```

**Review by nicolas-grekas — APPROVED** [review]

**Review by kbond — APPROVED** [review]
