### PR TITLE
[Map] Fix Google/Leaflet bridges when using Webpack Encore

### LINKED ISSUE #2105: [Leaflet] Error during installation
Module build failed: Module not found:
"./vendor/symfony/ux-leaflet-map/assets/dist/map_controller.js" contains a reference to the file "@symfony/ux-map/abstract-map-controller".
This file can not be found, please check it for typos or update it if the file got moved.

"./vendor/symfony/ux-leaflet-map/assets/dist/map_controller.js" contains a reference to the file "leaflet/dist/leaflet.min.css".
This file can not be found, please check it for typos or update it if the file got moved.

### PR DESCRIPTION
**Pull request by Kocal**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no 
| Issues        | Fix #2105 
| License       | MIT

This PR fixes #2105, and ensures Leaflet and GoogleMaps bridges are working fine with Webpack Encore.

To be sure:
1. I've created a new Symfony app (no `--webapp`), 
2. Installed Encore, Stimulus, and Map
3. Added `.addAliases({ 'leaflet/dist/leaflet.min.css': 'leaflet/dist/leaflet.css' })` and `.enableStimulusBridge('./assets/controllers.json')` in `webpack.config.js`
4. Created the Map (`new Map()`) and rendered it (`ux_map(map, { style: 'height: ...' })`)

I am able to display a Leaflet map:
image

And a GoogleMap maps: 
image

---

The Map rendered on ux.symfony.com is also working (after updating the `importmap.php` as documented):

image

### CODE REVIEW

File: src/Map/src/Bridge/Google/assets/dist/map_controller.js [hunk 1]
```diff
@@ -1,8 +1,48 @@
-import AbstractMapController from '@symfony/ux-map/abstract-map-controller';
+import { Controller } from '@hotwired/stimulus';
```
Comment (Kocal) [inline src/Map/src/Bridge/Google/assets/dist/map_controller.js:1]: Surely because Rollup has been able to resolve the file when using `import AbstractMapController from '@symfony/ux-map'`, the `AbstractMapController` is now inlined.

I'm fine with this, especially it removes one useless HTTP request.

Comment (smnandre) [reply src/Map/src/Bridge/Google/assets/dist/map_controller.js:1]: Great!

**Review by smnandre — APPROVED** [review]
Nice!

**Review by kbond — APPROVED** [review]
