### PR TITLE
[Icons] Add `ignore_not_found` config option

### LINKED ISSUE #2008: ux_icon triggers an exception when icon doesn't exists
### Description

The twig `ux_icon` function always triggers an exception when the icon name doesn't exists.

In my opinion, since icons are usually not a critical feature (most of the time only for design purpose), this should trigger an exception only in `dev` mode by default and the exception should be catched with an error message in logs in `prod` mode.

Maybe by adding an option to the UX Icons component to configure this?

### Example

I have a feature in my app where the admin can add icons to display in the app.
One icon has been added with a typo and this put few pages of our site down.

### PR DESCRIPTION
**Pull request by smnandre**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Issues        | Fix #2008
| License       | MIT

Allow to silence error during rendering when an icon is not found (then a warning is log)

### CODE REVIEW

File: src/Icons/src/Twig/UXIconRuntime.php [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+    /**
+     * @param array<string, bool|string> $attributes
+     */
+    public function renderIcon(string $name, array $attributes = []): string
+    {
+        try {
+            return $this->iconRenderer->renderIcon($name, $attributes);
+        } catch (IconNotFoundException $e) {
+            if ($this->ignoreNotFound) {
+                return '';
```
Comment (Seb33300) [inline src/Icons/src/Twig/UXIconRuntime.php:43]: Can you log the catched error?

**Review by Seb33300 — CHANGES_REQUESTED** [review]

File: src/Icons/src/DependencyInjection/UXIconsExtension.php [hunk 2]
```diff
@@ -58,6 +58,10 @@ public function getConfigTreeBuilder(): TreeBuilder
                         ->end()
                     ->end()
                 ->end()
+                ->booleanNode('ignore_not_found')
+                    ->info('Ignore error when an icon is not found.')
+                    ->defaultFalse()
```
Comment (yceruto) [inline src/Icons/src/DependencyInjection/UXIconsExtension.php:63]: It could default to `%kernel.debug%` here or in the recipe

File: src/Icons/src/Twig/UXIconRuntime.php [hunk 3]
```diff
@@ -0,0 +1,46 @@
...
+
+    /**
+     * @param array<string, bool|string> $attributes
+     */
+    public function renderIcon(string $name, array $attributes = []): string
+    {
+        try {
+            return $this->iconRenderer->renderIcon($name, $attributes);
+        } catch (IconNotFoundException $e) {
+            if ($this->ignoreNotFound) {
```
Comment (yceruto) [inline src/Icons/src/Twig/UXIconRuntime.php:41]: Because it's a Twig rendering context, I'm wondering if we should use `Environment::isStrictVariables()` instead. I can't picture a case where the `twig.strict_variables` config is different from `ux_icons.ignoreNotFound`. They serve the same purpose for me.

Comment (kbond) [reply src/Icons/src/Twig/UXIconRuntime.php:41]: I'm thinking this also, at least until we're asked for a separate config option.

File: src/Icons/src/DependencyInjection/UXIconsExtension.php (hunk 2 above)
Comment (smnandre) [reply src/Icons/src/DependencyInjection/UXIconsExtension.php:63]: I think the idea in #2008 was to default to "not kernel.debug". 

I this change anything in prod, in would be a BC break, so maybe the recipe is a good solution, indeed

File: src/Icons/src/Twig/UXIconRuntime.php (hunk 3 above)
Comment (smnandre) [reply src/Icons/src/Twig/UXIconRuntime.php:41]: If by "using Environment::isStrictVariables()" you mean "do _not_ throw if strictVariable  = false", this would be a BC break, no ?

Comment (yceruto) [reply src/Icons/src/Twig/UXIconRuntime.php:41]: Not throwing the exception in the prod env doesn't seem like a critical behavior change to me. In fact, that's exactly what the reporter is requesting (aligned with how Twig behaves). As suggested https://github.com/symfony/ux/pull/2023#discussion_r1701592117 we could log the error instead.

The configs (`strict_variables` and `ignore_not_found`) appear to be opposite due to their naming, but they actually represent the same concept/purpose.

**Comment by smnandre** [comment]
Update: add a logger / log a warning when icon is not found

**Comment by smnandre** [comment]
@kbond @yceruto 

--

I've been -more than once- told we cannot do this or that for way, way smaller BC breaks. 

But if you guys say it's ok, that's ok for me. 

--

`ignore_missing` exist in Twig (include, source) too. It was my inspiration here for the name ... and felt very similar 

Every other filter / function i know of throw in Twig when an error occurs

The only silent thing is for getAttribute.

To me an icon (which should be in cache) is nothing like an attribute on an (existing) object.

The asset function throw when an asset does not exist (example: a svg icon)

--

If we use strict_variables here, I _cannot_ have exception in prod for missing icons anymore. 

(i would need to set strict_variables to true -- something i don't desire for obvious reasons)

--

Not in the mood for the subtext of this discussion.. so just tell me your decision and i'll update the PR.

**Comment by kbond** [comment]
This looks fine to me as is!
