### PR TITLE
Disable cache warmup when translator is identity translator

### LINKED ISSUE #1962: [Translator] Warming up the cache fails when the translator is disabled.
When performing acceptance or unit tests, we disable the `translator` so the translated values will be the translation keys. This makes assertions easier, as we don't have to update the tests when the translations have been altered.

Right now, I'm facing the following issue:

```
TypeError {#46989
  #message: "Symfony\UX\Translator\CacheWarmer\TranslationsCacheWarmer::__construct(): Argument #1 ($translatorBag) must be of type Symfony\Component\Translation\TranslatorBagInterface, Symfony\Component\Translation\IdentityTranslator given, called in /srv/app/var/cache/test/ContainerWZcqQ3o/getUx_Translator_CacheWarmer_TranslationsCacheWarmerService.php on line 24"
  #code: 0
  #file: "./vendor/symfony/ux-translator/src/CacheWarmer/TranslationsCacheWarmer.php"
  #line: 25
  trace: {
    ./vendor/symfony/ux-translator/src/CacheWarmer/TranslationsCacheWarmer.php:25 { …}
    ./var/cache/test/ContainerWZcqQ3o/getUx_Translator_CacheWarmer_TranslationsCacheWarmerService.php:24 {
      ContainerWZcqQ3o\getUx_Translator_CacheWarmer_TranslationsCacheWarmerService::do($container, $lazyLoad = true)^
      › 
      ›     return $container->privates['ux.translator.cache_warmer.translations_cache_warmer'] = new \Symfony\UX\Translator\CacheWarmer\TranslationsCacheWarmer(($container->privates['translator'] ??= new \Symfony\Component\Translation\IdentityTranslator()), ($container->privates['ux.translator.translations_dumper'] ?? $container->load('getUx_Translator_TranslationsDumperService')));
      › }
    }
    ./var/cache/test/ContainerWZcqQ3o/KernelTestDebugContainer.php:1995 { …}
    ./var/cache/test/ContainerWZcqQ3o/getCacheWarmerService.php:37 { …}
    ./vendor/symfony/http-kernel/CacheWarmer/CacheWarmerAggregate.php:99 { …}
    ./vendor/symfony/http-kernel/Kernel.php:545 { …}
    ./vendor/symfony/http-kernel/Kernel.php:763 { …}
    ./vendor/symfony/http-kernel/Kernel.php:126 { …}
    ./src/Kernel.php:34 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:190 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:72 { …}
    ./vendor/symfony/console/Application.php:175 { …}
    ./vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:49 { …}
    ./vendor/autoload_runtime.php:29 { …}
    ./bin/console:11 { …}
  }
}
```

What would the proper and recommended way be to handle this?

### PR DESCRIPTION
**Pull request by SanderVerkuil**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| Issues        | Fix #1962
| License       | MIT

If the present `translator` does not implement the `TranslatorBag` interface, which is the case if the framework bundle is enabled and either the form, or the validator are enabled, removes the warmup phase.

### CODE REVIEW

File: src/Translator/src/DependencyInjection/TranslatorCompilerPass.php [hunk 1]
```diff
@@ -0,0 +1,32 @@
+<?php
+
+declare(strict_types=1);
```
Comment (smnandre) [inline src/Translator/src/DependencyInjection/TranslatorCompilerPass.php]:
```suggestion

```

There is no strict types in the Symfony codebase afaik

File: src/Translator/src/UxTranslatorBundle.php [hunk 2]
```diff
@@ -26,4 +28,9 @@ public function getPath(): string
     {
         return \dirname(__DIR__);
     }
+
+    public function build(ContainerBuilder $container)
```
Comment (smnandre) [inline src/Translator/src/UxTranslatorBundle.php]:
```suggestion
    public function build(ContainerBuilder $container): void
```

File: src/Translator/src/DependencyInjection/TranslatorCompilerPass.php [hunk 3]
```diff
@@ -0,0 +1,32 @@
...
+
+namespace Symfony\UX\Translator\DependencyInjection;
+
+use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
+use Symfony\Component\DependencyInjection\ContainerBuilder;
+use Symfony\Component\Translation\TranslatorBagInterface;
+
+class TranslatorCompilerPass implements CompilerPassInterface
+{
+    public function process(ContainerBuilder $container)
```
Comment (smnandre) [inline src/Translator/src/DependencyInjection/TranslatorCompilerPass.php]:
```suggestion
    public function process(ContainerBuilder $container): void
```

File: src/Translator/src/DependencyInjection/TranslatorCompilerPass.php [hunk 4]
```diff
@@ -0,0 +1,32 @@
...
+    {
+        if (!$this->hasValidTranslator($container)) {
+            $container->removeDefinition('ux.translator.cache_warmer.translations_cache_warmer');
+        }
+    }
+
+    private function hasValidTranslator(ContainerBuilder $containerBuilder): bool
```
Comment (smnandre) [inline src/Translator/src/DependencyInjection/TranslatorCompilerPass.php:18]: Do we need the method ?

**Comment by smnandre** [comment]
Thank you @SanderVerkuil !

Could you maybe add a line or two in the documentation ?

**Comment by smnandre** [comment]
@maelanleborgne @Kocal  if you can just confirm, as you know more than me this package :) ?

File: src/Translator/src/DependencyInjection/TranslatorCompilerPass.php (hunk 1 above)
Comment (SanderVerkuil) [reply src/Translator/src/DependencyInjection/TranslatorCompilerPass.php]: Alright, thanks! Removed the strict types.

File: src/Translator/src/UxTranslatorBundle.php (hunk 2 above)
Comment (SanderVerkuil) [reply src/Translator/src/UxTranslatorBundle.php]: Added the return type

File: src/Translator/src/DependencyInjection/TranslatorCompilerPass.php (hunk 3 above)
Comment (SanderVerkuil) [reply src/Translator/src/DependencyInjection/TranslatorCompilerPass.php]: Added the return type

File: src/Translator/src/DependencyInjection/TranslatorCompilerPass.php (hunk 4 above)
Comment (SanderVerkuil) [reply src/Translator/src/DependencyInjection/TranslatorCompilerPass.php:18]: I personally feel that this reads better than something like:

```php
public function process(ContainerBuilder $container): void
{
    if (!$container->hasDefinition('translator') || i!s_subclass_of($container->getDefinition('translator')->getClass(), TranslatorBagInterface::class)) {
        $container->removeDefinition('ux.translator.cache_warmer.translations_cache_warmer');
    }
}
```

or the alternative

```php
public function process(ContainerBuilder $container): void
{
    if (!$container->hasDefinition('translator')) {
        $container->removeDefinition('ux.translator.cache_warmer.translations_cache_warmer');
        return;
    }
    $translator = $container->getDefinition('translator');
    if (i!s_subclass_of($translator->getClass(), TranslatorBagInterface::class)) {
        $container->removeDefinition('ux.translator.cache_warmer.translations_cache_warmer');
        return;
    }
}

**Comment by SanderVerkuil** [comment]
> Thank you @SanderVerkuil !
> 
> Could you maybe add a line or two in the documentation ?

Done! Added a small note next to the cache warmup, feel free to modify it as you see fit, or if it's unclear I'd be happy to hear!

**Review by smnandre — APPROVED** [review]

**Review by kbond — APPROVED** [review]
Looks good, just waiting for a final confirmation from @Kocal.

**Review by Kocal — APPROVED** [review]
This looks fine to me, thanks for your contribution :)

**Comment by kbond** [comment]
This is great, thanks Sander!

File: src/Translator/doc/index.rst [hunk 5]
```diff
@@ -71,6 +71,10 @@ For a better developer experience, TypeScript types definitions are also generat
 Then, you will be able to import those JavaScript translations in your assets.
 Don't worry about your final bundle size, only the translations you use will be included in your final bundle, thanks to the `tree shaking <https://webpack.js.org/guides/tree-shaking/>`_.
 
+.. note::
+
+    This package requires the `translator` to be enabled in your Symfony application. If you don't use the `translator` service, the warmup command will not generate any translations.
```
Comment (alexisLefebvre) [inline src/Translator/doc/index.rst:76]: > This package requires the `translator` to be enabled

Is `translator` a package, a service of something else? In the next sentence it is written that it's a service, I think it should be explicit in the first sentence too.

Comment (alexisLefebvre) [reply src/Translator/doc/index.rst:76]: Code should have double quotes, otherwise it is displayed like this:

> image

Comment (alexisLefebvre) [reply src/Translator/doc/index.rst:76]: Side note: This PR may be reverted soon:

- #2060

Comment (SanderVerkuil) [reply src/Translator/doc/index.rst:76]: I've updated this note in #2061
