### PR TITLE
More precisely initializing services/config for asset mapper

### LINKED ISSUE #907: Can't upgrade 2.8.1 packages to 2.9.0
I'm not sure if the issue is with my setup, the new `symfony/stimulus-bundle`, or UX, but my service container won't build with any UX `2.9.0` packages installed. I can explicitly require `symfony/stimulus-bundle` `2.9.0` with UX `2.8.1` packages and all is fine, but upgrading UX packages results in service resolution errors.

`composer.json`:

image

Running a `composer update` results in:
```diff
  Gathering patches from patch file.
  Loading composer repositories with package information
  Restricting packages listed in "symfony/symfony" to "^6"
  Updating dependencies
  Lock file operations: 1 install, 6 updates, 0 removals
    - Upgrading symfony/flex (v2.3.0 => v2.3.1)
    - Locking symfony/stimulus-bundle (v2.9.0)
    - Upgrading symfony/ux-chartjs (v2.8.1 => v2.9.0)
    - Upgrading symfony/ux-dropzone (v2.8.1 => v2.9.0)
    - Upgrading symfony/ux-live-component (v2.8.1 => v2.9.0)
    - Upgrading symfony/ux-notify (v2.8.1 => v2.9.0)
    - Upgrading symfony/ux-turbo (v2.8.1 => v2.9.0)
  Writing lock file
  Installing dependencies from lock file (including require-dev)
  Package operations: 1 install, 6 updates, 0 removals
    - Downloading symfony/flex (v2.3.1)
    - Downloading symfony/stimulus-bundle (v2.9.0)
    - Downloading symfony/ux-chartjs (v2.9.0)
    - Downloading symfony/ux-dropzone (v2.9.0)
    - Downloading symfony/ux-live-component (v2.9.0)
    - Downloading symfony/ux-notify (v2.9.0)
    - Downloading symfony/ux-turbo (v2.9.0)
  Gathering patches from patch file.
  Gathering patches for dependencies. This might take a minute.
    - Upgrading symfony/flex (v2.3.0 => v2.3.1): Extracting archive
    - Installing symfony/stimulus-bundle (v2.9.0): Extracting archive
    - Upgrading symfony/ux-chartjs (v2.8.1 => v2.9.0): Extracting archive
    - Upgrading symfony/ux-dropzone (v2.8.1 => v2.9.0): Extracting archive
    - Upgrading symfony/ux-live-component (v2.8.1 => v2.9.0): Extracting archive
    - Upgrading symfony/ux-notify (v2.8.1 => v2.9.0): Extracting archive
    - Upgrading symfony/ux-turbo (v2.8.1 => v2.9.0): Extracting archive
  Package fgrosse/phpasn1 is abandoned, you should avoid using it. No replacement was suggested.
  Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead.
  Generating optimized autoload files
  157 packages you are using are looking for funding.
  Use the `composer fund` command to find out more!
  Endroid Installer detected project type "symfony"
  
  What about running composer global require symfony/thanks && composer thanks now?
  This will spread some 💖  by sending a ★  to the GitHub repositories of your fellow package maintainers.
  
  Run composer recipes at any time to see the status of your Symfony recipes.
  
  Executing script cache:clear [KO]
   [KO]
  Script cache:clear returned with error code 255
  !!  Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException {#16135
- !!    #message: "The service "chartjs.twig_extension" has a dependency on a non-existent service "stimulus.helper"."
  !!    #code: 0
  !!    #file: "/data/app/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php"
  !!    #line: 83
  !!    -id: "stimulus.helper"
  !!    -sourceId: "chartjs.twig_extension"
  !!    -alternatives: []
  !!    trace: {
  !!      /data/app/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:83 { …}
  !!      /data/app/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:80 { …}
  !!      /data/app/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:46 { …}
  !!      /data/app/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:89 { …}
  !!      /data/app/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:46 { …}
  !!      /data/app/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:80 { …}
  !!      /data/app/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:46 { …}
  !!      /data/app/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:44 { …}
  !!      /data/app/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:37 { …}
  !!      /data/app/vendor/symfony/dependency-injection/Compiler/Compiler.php:73 { …}
  !!      /data/app/vendor/symfony/dependency-injection/ContainerBuilder.php:721 { …}
  !!      /data/app/vendor/symfony/http-kernel/Kernel.php:499 { …}
  !!      /data/app/vendor/symfony/http-kernel/Kernel.php:721 { …}
  !!      /data/app/vendor/symfony/http-kernel/Kernel.php:123 { …}
  !!      ./src/App/Kernel.php:66 {
  !!        Moyer\App\Kernel->boot(): void
  !!        › {
  !!        ›     parent::boot();
  !!        › 
  !!      }
  !!      ./bin/console:44 { …}
  !!    }
  !!  }
  !!  2023-05-27T19:09:41+00:00 [critical] Uncaught Exception: The service "chartjs.twig_extension" has a dependency on a non-existent service "stimulus.helper".
  !!  
  Script @auto-scripts was called via post-update-cmd
```

Whereas this configuration works:

image

```diff
  Gathering patches from patch file.
  Loading composer repositories with package information
  Restricting packages listed in "symfony/symfony" to "^6"
  Updating dependencies
  Lock file operations: 1 install, 1 update, 0 removals
    - Upgrading symfony/flex (v2.3.0 => v2.3.1)
    - Locking symfony/stimulus-bundle (v2.9.0)
  Writing lock file
  Installing dependencies from lock file (including require-dev)
  Package operations: 0 installs, 1 update, 0 removals
  Gathering patches from patch file.
  Gathering patches for dependencies. This might take a minute.
    - Upgrading symfony/flex (v2.3.0 => v2.3.1): Extracting archive
  Package fgrosse/phpasn1 is abandoned, you should avoid using it. No replacement was suggested.
  Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead.
  Generating optimized autoload files
  157 packages you are using are looking for funding.
  Use the `composer fund` command to find out more!
  Endroid Installer detected project type "symfony"
  
  What about running composer global require symfony/thanks && composer thanks now?
  This will spread some 💖  by sending a ★  to the GitHub repositories of your fellow package maintainers.
  
  Run composer recipes at any time to see the status of your Symfony recipes.
  
+ Executing script cache:clear [OK]
  Executing script assets:install public [OK]
  
  No security vulnerability advisories found
```

### PR DESCRIPTION
**Pull request by weaverryan**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| Tickets       | Fix #907
| License       | MIT

Hi!

A few fixes for the new 2.9 version, which included a lot of under-the-hood changes to support asset mapper. These shouldn't be noticed by users and hopefully this will smooth out the final bumps:

A) Avoid prepending the `asset_mapper` config unless FWBundle 6.3 is present. I don't love the solution - but it should work well enough, especially as this applies to asset mapper users and that is still experimental.

B) Avoid registering a few asset mapper services that, on older versions of PHP/Symfony, may cause a container explosion due to a trait that won't be present.

C) Plug some holes in the CI to test lower deps. The CI really needs to become much more dynamic than it is now, but this makes sure that all packages are tested for highest/lowest deps.

Cheers!

### CODE REVIEW

File: src/Autocomplete/src/DependencyInjection/AutocompleteExtension.php [hunk 1]
```diff
@@ -155,4 +155,19 @@ private function registerFormServices(ContainerBuilder $container): void
...
+            return false;
+        }
+
+        // check that FrameworkBundle 6.3 or higher is installed
+        $bundlesMetadata = $container->getParameter('kernel.bundles_metadata');
+        if (!isset($bundlesMetadata['FrameworkBundle'])) {
+            return false;
+        }
+
+        return is_file($bundlesMetadata['FrameworkBundle']['path'].'/Resources/config/asset_mapper.php');
```
Comment (weaverryan) [inline src/Autocomplete/src/DependencyInjection/AutocompleteExtension.php:171]: @stof I don't love this solution, but I can't think of a better option. I'm wondering if, in asset-mapper 6.4, we should allow a service-based way of adding "paths" instead of relying on prepending.

**Comment by weaverryan** [comment]
Low deps on 8.1 are failing but should be good (I'll verify after the merge). The CI matrix doesn't patch (yet) cross-dependencies as well as symfony/symfony, so those bundles are not using StimulusBundle from this PR and are thus failing due to its prepend configuration acting when it shouldn't.

File: src/Autocomplete/src/DependencyInjection/AutocompleteExtension.php (hunk 1 above)
Comment (stof) [reply src/Autocomplete/src/DependencyInjection/AutocompleteExtension.php:171]: I don't have a better idea for that for now
